import { useEffect, useState } from 'react';
import { AlertCircle, CheckCircle2, FileCheck2 } from 'lucide-react';
import { api } from '@/lib/api';
import { formatDateTime } from '@/lib/utils';
import { useParams } from '@/lib/router';
import type { ESignCertificateVerification } from '@/types';

export function CertificateVerificationPage() {
  const { certificateId = '' } = useParams(); const [result, setResult] = useState<ESignCertificateVerification | null>(null); const [error, setError] = useState('');
  useEffect(() => { api<ESignCertificateVerification>(`/api/public/esign/certificates/${encodeURIComponent(certificateId)}`).then(setResult).catch((reason) => setError(reason instanceof Error ? reason.message : 'Certificate not found.')); }, [certificateId]);
  return <div className="min-h-screen bg-background"><header className="flex h-14 items-center border-b bg-card px-4 sm:px-6"><div className="grid h-7 w-7 place-items-center rounded-md bg-primary text-xs font-bold text-primary-foreground">S</div><div className="ml-2 text-sm font-semibold">Seemplify eSignature</div></header><main className="mx-auto max-w-2xl px-4 py-12"><div className="border bg-card p-6 sm:p-8">{error ? <><AlertCircle className="h-7 w-7 text-destructive" /><h1 className="mt-4 text-xl font-semibold">Certificate not verified</h1><p className="mt-2 text-sm text-muted-foreground">{error}</p></> : !result ? <div className="h-56 animate-pulse bg-muted" /> : <><div className="flex items-center gap-3">{result.valid ? <CheckCircle2 className="h-7 w-7 text-emerald-700" /> : <AlertCircle className="h-7 w-7 text-destructive" />}<h1 className="text-xl font-semibold">{result.valid ? 'Certificate verified' : 'Certificate not verified'}</h1></div><dl className="mt-6 divide-y border text-sm"><div className="grid gap-1 px-4 py-3 sm:grid-cols-[160px_1fr]"><dt className="text-muted-foreground">Certificate ID</dt><dd className="break-all font-mono text-xs">{result.certificateId}</dd></div><div className="grid gap-1 px-4 py-3 sm:grid-cols-[160px_1fr]"><dt className="text-muted-foreground">Agreement</dt><dd className="break-all font-mono text-xs">{result.envelopeId}</dd></div><div className="grid gap-1 px-4 py-3 sm:grid-cols-[160px_1fr]"><dt className="text-muted-foreground">Completed</dt><dd>{result.completedAt ? formatDateTime(result.completedAt) : 'Not completed'}</dd></div><div className="grid gap-1 px-4 py-3 sm:grid-cols-[160px_1fr]"><dt className="text-muted-foreground">Document hash</dt><dd className="break-all font-mono text-xs">{result.documentHash}</dd></div></dl><div className="mt-6 flex gap-3 text-sm text-muted-foreground"><FileCheck2 className="h-4 w-4 shrink-0" /><p>This page verifies the server-issued completion record. It does not expose the agreement or recipient email addresses.</p></div></>}</div></main></div>;
}
