import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { Download, GitCompare, LoaderCircle, Plus, RefreshCw, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { JourneyBlueprintMeasurementPanel } from '@/components/journeys/JourneyBlueprintMeasurementPanel';
import { JourneyWorkspaceSavedViewBar } from '@/components/journeys/JourneyWorkspaceSavedViewBar';
import { useAuthSession, useSessionFeature } from '@/lib/authSessionContext';
import { listJourneyMaps, readJourneyMap, type JourneyDefinitionSummary } from '@/lib/journeyMaps';
import { listJourneyPortfolioItems, type JourneyPortfolioItem } from '@/lib/journeyPortfolio';
import type { JourneyBlueprintViewConfiguration } from '@/lib/journeyWorkspaceSavedViews';
import {
  analyseJourneyServiceBlueprint, compareJourneyServiceBlueprintVersions, createJourneyBlueprintResource,
  createJourneyServiceBlueprint, createJourneyServiceBlueprintVersion, downloadJourneyServiceBlueprintVersion,
  journeyBlueprintElementKinds,
  journeyBlueprintGapReviewStates, journeyBlueprintLanes, journeyBlueprintLifecycles, journeyBlueprintRelationshipKinds,
  journeyBlueprintResourceKinds, journeyBlueprintReviewStates, journeyBlueprintStates, listJourneyBlueprintResources,
  listJourneyServiceBlueprints, listJourneyServiceBlueprintVersions, readJourneyServiceBlueprintVersion,
  reviewJourneyBlueprintGap, reviewJourneyServiceBlueprintVersion, updateJourneyBlueprintResource,
  updateJourneyServiceBlueprint, type JourneyBlueprint, type JourneyBlueprintAnalysis, type JourneyBlueprintComparison,
  type JourneyBlueprintElement, type JourneyBlueprintElementKind, type JourneyBlueprintLane,
  type JourneyBlueprintPortfolioLink, type JourneyBlueprintRelationship, type JourneyBlueprintRelationshipKind, type JourneyBlueprintResource,
  type JourneyBlueprintResourceKind, type JourneyBlueprintStage, type JourneyBlueprintVersion,
  type JourneyBlueprintVersionSummary
} from '@/lib/journeyServiceBlueprint';

const laneLabels: Record<JourneyBlueprintLane, string> = { customer: 'Customer actions', frontstage: 'Frontstage', backstage: 'Backstage', supporting_system: 'Supporting systems', policy_control: 'Policies and controls' };
const boundaryAfter: Partial<Record<JourneyBlueprintLane, string>> = { customer: 'Line of interaction', frontstage: 'Line of visibility', backstage: 'Line of internal interaction' };
const titleCase = (value: string) => value.replaceAll('_', ' ').replace(/^./u, (letter) => letter.toUpperCase());
const errorMessage = (reason: unknown, fallback: string) => reason instanceof Error && reason.message ? reason.message : fallback;
const optionalNumber = (value: string) => value.trim() === '' ? null : Number(value);

type Draft = { journeyVersionId: string; state: 'current' | 'future'; changeReason: string; stages: JourneyBlueprintStage[]; elements: JourneyBlueprintElement[]; relationships: JourneyBlueprintRelationship[]; portfolioLinks: JourneyBlueprintPortfolioLink[] };
type ElementForm = { id: string; stageKey: string; lane: JourneyBlueprintLane; kind: JourneyBlueprintElementKind; title: string; description: string; ownerTeamId: string; actorId: string; systemId: string; vendorId: string; controlId: string; slaMinutes: string; unitCost: string; riskProbability: string; riskImpact: string; evidenceRefs: string; metricRefs: string };
const emptyElement = (stageKey = ''): ElementForm => ({ id: '', stageKey, lane: 'customer', kind: 'action', title: '', description: '', ownerTeamId: '', actorId: '', systemId: '', vendorId: '', controlId: '', slaMinutes: '', unitCost: '', riskProbability: '', riskImpact: '', evidenceRefs: '', metricRefs: '' });

function BlueprintGrid({ draft, onSelect }: { draft: Draft; onSelect: (element: JourneyBlueprintElement) => void }) {
  return <div className="max-w-full overflow-x-auto border" data-testid="journey-service-blueprint-table">
    <table className="w-full min-w-[900px] border-collapse text-left text-sm">
      <caption className="sr-only">Service blueprint stages by customer, frontstage, backstage, supporting system, and policy or control lane</caption>
      <thead><tr className="border-b bg-muted/50"><th scope="col" className="sticky left-0 z-10 w-44 border-r bg-muted px-3 py-2">Lane</th>{draft.stages.map((stage) => <th scope="col" className="min-w-52 border-r px-3 py-2" key={stage.stageKey}>{stage.name}</th>)}</tr></thead>
      <tbody>{journeyBlueprintLanes.flatMap((lane) => {
        const row = <tr className="border-b align-top" key={lane}><th scope="row" className="sticky left-0 z-10 border-r bg-background px-3 py-3 font-medium">{laneLabels[lane]}</th>{draft.stages.map((stage) => <td className="border-r p-2" key={stage.stageKey}><div className="grid gap-2">{draft.elements.filter((element) => element.lane === lane && element.stageKey === stage.stageKey).sort((a, b) => (a.ordinal || 0) - (b.ordinal || 0)).map((element) => <button type="button" className="border bg-card px-3 py-2 text-left hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" key={element.id} onClick={() => onSelect(element)}><span className="block font-medium">{element.title}</span><span className="mt-0.5 block text-xs text-muted-foreground">{titleCase(element.kind)}</span></button>)}</div></td>)}</tr>;
        const boundary = boundaryAfter[lane];
        return boundary ? [row, <tr aria-label={boundary} className="border-b" key={`${lane}-boundary`}><th scope="row" className="sticky left-0 z-10 border-r bg-background px-3 py-1 text-xs font-medium text-muted-foreground">{boundary}</th><td colSpan={draft.stages.length} className="border-t-2 border-dashed border-foreground/40 py-1"><span className="sr-only">{boundary} boundary across every stage</span></td></tr>] : [row];
      })}</tbody>
    </table>
    {draft.stages.length === 0 && <p className="p-4 text-sm text-muted-foreground">No stages are available for this version.</p>}
  </div>;
}

function ElementEditor({ draft, resources, canManage, onChange }: { draft: Draft; resources: JourneyBlueprintResource[]; canManage: boolean; onChange: (next: Draft) => void }) {
  const [form, setForm] = useState<ElementForm>(() => emptyElement(draft.stages[0]?.stageKey));
  const set = (key: keyof ElementForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const select = (element: JourneyBlueprintElement) => setForm({ ...emptyElement(element.stageKey), ...element, description: element.description || '', ownerTeamId: element.ownerTeamId || '', actorId: element.actorId || '', systemId: element.systemId || '', vendorId: element.vendorId || '', controlId: element.controlId || '', slaMinutes: element.slaMinutes?.toString() || '', unitCost: element.unitCost?.toString() || '', riskProbability: element.riskProbability?.toString() || '', riskImpact: element.riskImpact?.toString() || '', evidenceRefs: (element.evidenceRefs || []).join(', '), metricRefs: (element.metricRefs || []).join(', ') });
  function save(event: FormEvent) {
    event.preventDefault();
    const id = form.id || crypto.randomUUID();
    const element: JourneyBlueprintElement = { id, stageKey: form.stageKey, lane: form.lane, kind: form.kind, title: form.title.trim(), description: form.description.trim(), ownerTeamId: form.ownerTeamId || null, actorId: form.actorId || null, systemId: form.systemId || null, vendorId: form.vendorId || null, controlId: form.controlId || null, slaMinutes: optionalNumber(form.slaMinutes), unitCost: optionalNumber(form.unitCost), riskProbability: optionalNumber(form.riskProbability), riskImpact: optionalNumber(form.riskImpact), ordinal: form.id ? draft.elements.find((item) => item.id === id)?.ordinal ?? 0 : draft.elements.filter((item) => item.stageKey === form.stageKey && item.lane === form.lane).length, evidenceRefs: form.evidenceRefs.split(',').map((value) => value.trim()).filter(Boolean), metricRefs: form.metricRefs.split(',').map((value) => value.trim()).filter(Boolean) };
    onChange({ ...draft, elements: [...draft.elements.filter((item) => item.id !== id), element], relationships: draft.relationships });
    setForm(emptyElement(form.stageKey));
  }
  const resourceOptions = (kind: JourneyBlueprintResourceKind) => resources.filter((resource) => resource.kind === kind && resource.lifecycle === 'active');
  return <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
    <div className="min-w-0"><BlueprintGrid draft={draft} onSelect={select} /><section className="mt-5 overflow-x-auto border" aria-labelledby="blueprint-elements-alternative"><h2 id="blueprint-elements-alternative" className="border-b px-4 py-3 text-sm font-semibold">Element list</h2><table className="w-full min-w-[720px] text-left text-sm"><caption className="sr-only">Keyboard-accessible service blueprint element list</caption><thead className="border-b bg-muted/50"><tr><th className="px-3 py-2">Title</th><th className="px-3 py-2">Stage</th><th className="px-3 py-2">Lane</th><th className="px-3 py-2">Kind</th><th className="px-3 py-2">Action</th></tr></thead><tbody>{draft.elements.map((element) => <tr className="border-b last:border-0" key={element.id}><td className="px-3 py-2 font-medium">{element.title}</td><td className="px-3 py-2">{draft.stages.find((stage) => stage.stageKey === element.stageKey)?.name || element.stageKey}</td><td className="px-3 py-2">{laneLabels[element.lane]}</td><td className="px-3 py-2">{titleCase(element.kind)}</td><td className="px-3 py-2"><Button type="button" size="sm" variant="outline" onClick={() => select(element)}>Edit</Button></td></tr>)}</tbody></table>{draft.elements.length === 0 && <p className="p-4 text-sm text-muted-foreground">No elements have been authored.</p>}</section></div>
    {canManage && <form className="h-fit min-w-0 border p-4" onSubmit={save} aria-labelledby="element-editor-heading"><h2 id="element-editor-heading" className="text-sm font-semibold">{form.id ? 'Edit element' : 'Add element'}</h2><div className="mt-3 grid gap-3">
      <div className="grid gap-1.5"><Label htmlFor="blueprint-element-title">Title</Label><Input id="blueprint-element-title" required maxLength={200} value={form.title} onChange={(event) => set('title', event.target.value)} /></div>
      <div className="grid grid-cols-2 gap-3"><div className="grid gap-1.5"><Label htmlFor="blueprint-element-stage">Stage</Label><select id="blueprint-element-stage" required className="h-9 min-w-0 rounded-md border bg-background px-2 text-sm" value={form.stageKey} onChange={(event) => set('stageKey', event.target.value)}>{draft.stages.map((stage) => <option key={stage.stageKey} value={stage.stageKey}>{stage.name}</option>)}</select></div><div className="grid gap-1.5"><Label htmlFor="blueprint-element-lane">Lane</Label><select id="blueprint-element-lane" className="h-9 min-w-0 rounded-md border bg-background px-2 text-sm" value={form.lane} onChange={(event) => set('lane', event.target.value)}>{journeyBlueprintLanes.map((lane) => <option key={lane} value={lane}>{laneLabels[lane]}</option>)}</select></div></div>
      <div className="grid gap-1.5"><Label htmlFor="blueprint-element-kind">Kind</Label><select id="blueprint-element-kind" className="h-9 rounded-md border bg-background px-2 text-sm" value={form.kind} onChange={(event) => set('kind', event.target.value)}>{journeyBlueprintElementKinds.map((kind) => <option key={kind} value={kind}>{titleCase(kind)}</option>)}</select></div>
      <div className="grid gap-1.5"><Label htmlFor="blueprint-element-description">Description</Label><textarea id="blueprint-element-description" className="min-h-20 rounded-md border bg-background px-3 py-2 text-sm" maxLength={10_000} value={form.description} onChange={(event) => set('description', event.target.value)} /></div>
      {[['ownerTeamId', 'Owning team', 'team'], ['actorId', 'Actor', 'actor'], ['systemId', 'System', 'system'], ['vendorId', 'Vendor', 'vendor'], ['controlId', 'Control', 'control']].map(([field, label, kind]) => <div className="grid gap-1.5" key={field}><Label htmlFor={`blueprint-${field}`}>{label}</Label><select id={`blueprint-${field}`} className="h-9 rounded-md border bg-background px-2 text-sm" value={form[field as keyof ElementForm]} onChange={(event) => set(field as keyof ElementForm, event.target.value)}><option value="">None</option>{resourceOptions(kind as JourneyBlueprintResourceKind).map((resource) => <option value={resource.id} key={resource.id}>{resource.name}</option>)}</select></div>)}
      <div className="grid grid-cols-2 gap-3">{[['slaMinutes', 'SLA minutes'], ['unitCost', 'Unit cost'], ['riskProbability', 'Risk probability'], ['riskImpact', 'Risk impact']].map(([field, label]) => <div className="grid gap-1.5" key={field}><Label htmlFor={`blueprint-${field}`}>{label}</Label><Input id={`blueprint-${field}`} type="number" min="0" max={field.startsWith('risk') ? '1' : undefined} step={field.startsWith('risk') ? '0.01' : 'any'} value={form[field as keyof ElementForm]} onChange={(event) => set(field as keyof ElementForm, event.target.value)} /></div>)}</div>
      <div className="grid gap-1.5"><Label htmlFor="blueprint-evidence">Evidence reference IDs</Label><Input id="blueprint-evidence" placeholder="Comma-separated IDs" value={form.evidenceRefs} onChange={(event) => set('evidenceRefs', event.target.value)} /></div><div className="grid gap-1.5"><Label htmlFor="blueprint-metrics">Metric reference IDs</Label><Input id="blueprint-metrics" placeholder="Comma-separated IDs" value={form.metricRefs} onChange={(event) => set('metricRefs', event.target.value)} /></div>
      <div className="flex gap-2"><Button type="submit" disabled={!form.title.trim() || !form.stageKey}><Save className="h-4 w-4" />Save element</Button>{form.id && <Button type="button" variant="outline" onClick={() => { onChange({ ...draft, elements: draft.elements.filter((item) => item.id !== form.id), relationships: draft.relationships.filter((item) => item.fromElementId !== form.id && item.toElementId !== form.id) }); setForm(emptyElement(draft.stages[0]?.stageKey)); }}>Remove</Button>}</div>
    </div></form>}
  </div>;
}

function RelationshipEditor({ draft, canManage, onChange }: { draft: Draft; canManage: boolean; onChange: (draft: Draft) => void }) {
  const [kind, setKind] = useState<JourneyBlueprintRelationshipKind>('supports'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [label, setLabel] = useState('');
  function submit(event: FormEvent) { event.preventDefault(); onChange({ ...draft, relationships: [...draft.relationships, { id: crypto.randomUUID(), kind, fromElementId: from, toElementId: to, label: label.trim() }] }); setTo(''); setLabel(''); }
  const elementName = (id: string) => draft.elements.find((element) => element.id === id)?.title || 'Unavailable element';
  return <div className="grid min-w-0 gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="overflow-x-auto border" data-testid="journey-blueprint-relationships"><table className="w-full min-w-[680px] text-left text-sm"><caption className="sr-only">Service blueprint element relationships</caption><thead className="border-b bg-muted/50"><tr><th className="px-3 py-2">From</th><th className="px-3 py-2">Relationship</th><th className="px-3 py-2">To</th><th className="px-3 py-2">Label</th><th className="px-3 py-2">Action</th></tr></thead><tbody>{draft.relationships.map((relationship) => <tr className="border-b last:border-0" key={relationship.id}><td className="px-3 py-2">{elementName(relationship.fromElementId)}</td><td className="px-3 py-2">{titleCase(relationship.kind)}</td><td className="px-3 py-2">{elementName(relationship.toElementId)}</td><td className="px-3 py-2 text-muted-foreground">{relationship.label || '—'}</td><td className="px-3 py-2">{canManage ? <Button size="sm" variant="outline" onClick={() => onChange({ ...draft, relationships: draft.relationships.filter((item) => item.id !== relationship.id) })}>Remove</Button> : 'Read only'}</td></tr>)}</tbody></table>{draft.relationships.length === 0 && <p className="p-4 text-sm text-muted-foreground">No element relationships have been authored.</p>}</div>
    {canManage && <form className="h-fit border p-4" onSubmit={submit}><h2 className="text-sm font-semibold">Add relationship</h2><div className="mt-3 grid gap-3"><div className="grid gap-1.5"><Label htmlFor="blueprint-relationship-kind">Relationship</Label><select id="blueprint-relationship-kind" className="h-9 rounded-md border bg-background px-2 text-sm" value={kind} onChange={(event) => setKind(event.target.value as JourneyBlueprintRelationshipKind)}>{journeyBlueprintRelationshipKinds.map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select></div>{[['from', from, setFrom], ['to', to, setTo]].map(([key, value, setter]) => <div className="grid gap-1.5" key={key as string}><Label htmlFor={`blueprint-relationship-${key}`}>{titleCase(key as string)} element</Label><select id={`blueprint-relationship-${key}`} required className="h-9 rounded-md border bg-background px-2 text-sm" value={value as string} onChange={(event) => (setter as (value: string) => void)(event.target.value)}><option value="">Choose element</option>{draft.elements.filter((element) => key === 'from' || element.id !== from).map((element) => <option value={element.id} key={element.id}>{element.title}</option>)}</select></div>)}<div className="grid gap-1.5"><Label htmlFor="blueprint-relationship-label">Label</Label><Input id="blueprint-relationship-label" maxLength={500} value={label} onChange={(event) => setLabel(event.target.value)} /></div><Button type="submit" disabled={!from || !to || from === to}><Plus className="h-4 w-4" />Add relationship</Button></div></form>}
  </div>;
}

const portfolioRelationships = ['causes', 'affected_by', 'mitigated_by', 'improved_by'] as const;
type PortfolioRelationship = typeof portfolioRelationships[number];
const allowedPortfolioKinds: Record<PortfolioRelationship, JourneyPortfolioItem['kind'][]> = {
  causes: ['pain_point'], affected_by: ['pain_point', 'opportunity'],
  mitigated_by: ['solution', 'initiative'], improved_by: ['solution', 'initiative']
};

function PortfolioCausalityEditor({ draft, items, canManage, onChange }: {
  draft: Draft; items: JourneyPortfolioItem[]; canManage: boolean; onChange: (draft: Draft) => void;
}) {
  const [elementId, setElementId] = useState(''); const [itemId, setItemId] = useState('');
  const [relationship, setRelationship] = useState<PortfolioRelationship>('causes');
  const candidates = items.filter((item) => item.state === 'active' && allowedPortfolioKinds[relationship].includes(item.kind));
  const itemName = (id: string) => items.find((item) => item.id === id)?.title || id;
  const elementName = (id: string) => draft.elements.find((element) => element.id === id)?.title || id;
  function submit(event: FormEvent) {
    event.preventDefault();
    const item = items.find((candidate) => candidate.id === itemId);
    if (!item || !elementId) return;
    const link: JourneyBlueprintPortfolioLink = { id: crypto.randomUUID(), elementId, portfolioItemId: item.id,
      portfolioItemKind: item.kind, portfolioItemRevision: item.revision, relationship };
    onChange({ ...draft, portfolioLinks: [...draft.portfolioLinks, link] }); setItemId('');
  }
  return <div className="grid min-w-0 gap-5 lg:grid-cols-[minmax(0,1fr)_340px]">
    <div className="overflow-x-auto border"><table className="w-full min-w-[720px] text-left text-sm">
      <caption className="sr-only">Pinned service blueprint links to portfolio items</caption>
      <thead className="border-b bg-muted/50"><tr><th className="px-3 py-2">Blueprint element</th><th className="px-3 py-2">Relationship</th><th className="px-3 py-2">Portfolio item</th><th className="px-3 py-2">Pinned revision</th><th className="px-3 py-2">Action</th></tr></thead>
      <tbody>{draft.portfolioLinks.map((link) => <tr className="border-b last:border-0" key={link.id}><td className="px-3 py-2 font-medium">{elementName(link.elementId)}</td><td className="px-3 py-2">{titleCase(link.relationship)}</td><td className="px-3 py-2">{itemName(link.portfolioItemId)}<span className="ml-1 text-xs text-muted-foreground">({titleCase(link.portfolioItemKind)})</span></td><td className="px-3 py-2">{link.portfolioItemRevision}</td><td className="px-3 py-2">{canManage ? <Button size="sm" variant="outline" onClick={() => onChange({ ...draft, portfolioLinks: draft.portfolioLinks.filter((entry) => entry.id !== link.id) })}>Remove</Button> : 'Read only'}</td></tr>)}</tbody>
    </table>{draft.portfolioLinks.length === 0 && <p className="p-4 text-sm text-muted-foreground">No portfolio causality links have been authored.</p>}</div>
    {canManage && <form className="h-fit border p-4" onSubmit={submit} aria-labelledby="portfolio-causality-heading"><h2 id="portfolio-causality-heading" className="text-sm font-semibold">Add portfolio link</h2><div className="mt-3 grid gap-3">
      <div className="grid gap-1.5"><Label htmlFor="portfolio-causality-element">Blueprint element</Label><select id="portfolio-causality-element" required className="h-9 rounded-md border bg-background px-2 text-sm" value={elementId} onChange={(event) => setElementId(event.target.value)}><option value="">Choose element</option>{draft.elements.map((element) => <option key={element.id} value={element.id}>{element.title} · {laneLabels[element.lane]}</option>)}</select></div>
      <div className="grid gap-1.5"><Label htmlFor="portfolio-causality-relationship">Relationship</Label><select id="portfolio-causality-relationship" className="h-9 rounded-md border bg-background px-2 text-sm" value={relationship} onChange={(event) => { setRelationship(event.target.value as PortfolioRelationship); setItemId(''); }}>{portfolioRelationships.map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select></div>
      <div className="grid gap-1.5"><Label htmlFor="portfolio-causality-item">Exact portfolio item</Label><select id="portfolio-causality-item" required className="h-9 rounded-md border bg-background px-2 text-sm" value={itemId} onChange={(event) => setItemId(event.target.value)}><option value="">Choose item</option>{candidates.map((item) => <option key={item.id} value={item.id}>{item.title} · revision {item.revision}</option>)}</select></div>
      <Button type="submit" disabled={!elementId || !itemId}><Plus className="h-4 w-4" />Add pinned link</Button>
    </div></form>}
  </div>;
}

function AnalysisPanel({ analysis, version, canManage, onReviewGap }: { analysis: JourneyBlueprintAnalysis | null; version: JourneyBlueprintVersion; canManage: boolean; onReviewGap: (id: string, state: typeof journeyBlueprintGapReviewStates[number]) => Promise<void> }) {
  if (!analysis) return <p className="text-sm text-muted-foreground">Analysis is unavailable for this version.</p>;
  const coverage = analysis.coverage;
  return <div className="grid gap-5"><section className="border" aria-labelledby="coverage-heading"><h2 id="coverage-heading" className="border-b px-4 py-3 text-sm font-semibold">Coverage</h2><dl className="grid gap-px bg-border sm:grid-cols-3"><div className="bg-background p-4"><dt className="text-xs text-muted-foreground">Frontstage support</dt><dd className="mt-1 font-semibold">{coverage.supportedFrontstageElements} of {coverage.frontstageElements}</dd></div><div className="bg-background p-4"><dt className="text-xs text-muted-foreground">Backstage system support</dt><dd className="mt-1 font-semibold">{coverage.systemSupportedBackstageElements} of {coverage.backstageElements}</dd></div><div className="bg-background p-4"><dt className="text-xs text-muted-foreground">Mitigated failures</dt><dd className="mt-1 font-semibold">{coverage.mitigatedFailurePoints} of {coverage.failurePoints}</dd></div></dl></section>
    <section className="overflow-x-auto border" aria-labelledby="risk-heading"><h2 id="risk-heading" className="border-b px-4 py-3 text-sm font-semibold">Risk</h2><table className="w-full min-w-[520px] text-left text-sm"><caption className="sr-only">Calculated risk by blueprint element</caption><thead className="border-b bg-muted/50"><tr><th className="px-3 py-2">Element</th><th className="px-3 py-2">Probability</th><th className="px-3 py-2">Impact</th><th className="px-3 py-2">Score</th></tr></thead><tbody>{analysis.risk.map((risk) => <tr className="border-b last:border-0" key={risk.elementId}><td className="px-3 py-2">{version.elements.find((element) => element.id === risk.elementId)?.title || risk.elementId}</td><td className="px-3 py-2">{risk.probability}</td><td className="px-3 py-2">{risk.impact}</td><td className="px-3 py-2 font-medium">{risk.score}</td></tr>)}</tbody></table>{analysis.risk.length === 0 && <p className="p-4 text-sm text-muted-foreground">No quantified risks are present.</p>}</section>
    <section className="border" aria-labelledby="causality-heading"><h2 id="causality-heading" className="border-b px-4 py-3 text-sm font-semibold">Causality</h2><div className="p-4 text-sm"><p>{analysis.causality.fullyTracedPainPoints} of {analysis.causality.painPointTraces.length} linked pain points are fully traced.</p>{analysis.crossings.length > 0 && <p className="mt-2 text-muted-foreground">{analysis.crossings.length} relationship{analysis.crossings.length === 1 ? '' : 's'} cross explicit blueprint boundaries.</p>}</div></section>
    <section className="overflow-x-auto border" aria-labelledby="issues-heading"><h2 id="issues-heading" className="border-b px-4 py-3 text-sm font-semibold">Issues and persisted gap review</h2><table className="w-full min-w-[760px] text-left text-sm"><caption className="sr-only">Blueprint analysis issues and persisted gap states</caption><thead className="border-b bg-muted/50"><tr><th className="px-3 py-2">Severity</th><th className="px-3 py-2">Issue</th><th className="px-3 py-2">Gap</th><th className="px-3 py-2">Review</th></tr></thead><tbody>{analysis.issues.map((issue, index) => { const gap = version.gaps.find((item) => item.reasonCode === issue.code && item.targetElementId === (issue.elementId || null) && item.targetRelationshipId === (issue.relationshipId || null)); return <tr className="border-b last:border-0" key={`${issue.code}-${index}`}><td className="px-3 py-2">{titleCase(issue.severity)}</td><td className="px-3 py-2"><span className="font-medium">{issue.message}</span><span className="mt-0.5 block text-xs text-muted-foreground">{issue.code}</span></td><td className="px-3 py-2">{gap ? `${titleCase(gap.gapType)} · ${titleCase(gap.state)}` : 'Not persisted as a gap'}</td><td className="px-3 py-2">{gap?.state === 'open' && canManage ? <select aria-label={`Review gap ${issue.message}`} className="h-8 rounded-md border bg-background px-2" defaultValue="" onChange={(event) => event.target.value && void onReviewGap(gap.id, event.target.value as typeof journeyBlueprintGapReviewStates[number])}><option value="">Choose outcome</option>{journeyBlueprintGapReviewStates.map((state) => <option key={state} value={state}>{titleCase(state)}</option>)}</select> : gap ? titleCase(gap.state) : '—'}</td></tr>; })}</tbody></table>{analysis.issues.length === 0 && <p className="p-4 text-sm text-muted-foreground">No analysis issues were found.</p>}</section>
  </div>;
}

function ResourceCatalogue({ resources, canManage, busy, onCreate, onToggle }: { resources: JourneyBlueprintResource[]; canManage: boolean; busy: boolean; onCreate: (input: { kind: JourneyBlueprintResourceKind; name: string; description?: string }) => Promise<void>; onToggle: (resource: JourneyBlueprintResource) => Promise<void> }) {
  const [kind, setKind] = useState<JourneyBlueprintResourceKind>('team'); const [name, setName] = useState(''); const [description, setDescription] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); await onCreate({ kind, name: name.trim(), description: description.trim() }); setName(''); setDescription(''); }
  return <div className="grid min-w-0 gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="overflow-x-auto border"><table className="w-full min-w-[640px] text-left text-sm"><caption className="sr-only">Service blueprint resource catalogue</caption><thead className="border-b bg-muted/50"><tr><th className="px-3 py-2">Resource</th><th className="px-3 py-2">Kind</th><th className="px-3 py-2">Description</th><th className="px-3 py-2">Lifecycle</th></tr></thead><tbody>{resources.map((resource) => <tr className="border-b last:border-0" key={resource.id}><td className="px-3 py-2 font-medium">{resource.name}</td><td className="px-3 py-2">{titleCase(resource.kind)}</td><td className="px-3 py-2 text-muted-foreground">{resource.description || '—'}</td><td className="px-3 py-2">{canManage ? <Button size="sm" variant="outline" disabled={busy} onClick={() => void onToggle(resource)}>{resource.lifecycle === 'active' ? 'Retire' : 'Reactivate'}</Button> : titleCase(resource.lifecycle)}</td></tr>)}</tbody></table>{resources.length === 0 && <p className="p-4 text-sm text-muted-foreground">No resources have been created.</p>}</div>{canManage && <form className="h-fit border p-4" onSubmit={submit}><h2 className="text-sm font-semibold">Add catalogue resource</h2><div className="mt-3 grid gap-3"><div className="grid gap-1.5"><Label htmlFor="resource-kind">Kind</Label><select id="resource-kind" className="h-9 rounded-md border bg-background px-2 text-sm" value={kind} onChange={(event) => setKind(event.target.value as JourneyBlueprintResourceKind)}>{journeyBlueprintResourceKinds.map((value) => <option key={value}>{value}</option>)}</select></div><div className="grid gap-1.5"><Label htmlFor="resource-name">Name</Label><Input id="resource-name" required maxLength={200} value={name} onChange={(event) => setName(event.target.value)} /></div><div className="grid gap-1.5"><Label htmlFor="resource-description">Description</Label><textarea id="resource-description" className="min-h-20 rounded-md border bg-background px-3 py-2 text-sm" maxLength={5000} value={description} onChange={(event) => setDescription(event.target.value)} /></div><Button type="submit" disabled={busy || !name.trim()}><Plus className="h-4 w-4" />Add resource</Button></div></form>}</div>;
}

export function JourneyServiceBlueprintPage() {
  const enabled = useSessionFeature('journeyBlueprints'); const exportsEnabled = useSessionFeature('journeyExports');
  const metricsEnabled = useSessionFeature('journeyMetrics');
  const portfolioEnabled = useSessionFeature('journeyPortfolio');
  const session = useAuthSession(); const canManage = Boolean(session?.activeSpace && session.activeSpace.role !== 'member');
  const [blueprints, setBlueprints] = useState<JourneyBlueprint[]>([]); const [resources, setResources] = useState<JourneyBlueprintResource[]>([]); const [journeys, setJourneys] = useState<JourneyDefinitionSummary[]>([]); const [portfolioItems, setPortfolioItems] = useState<JourneyPortfolioItem[]>([]);
  const [selectedId, setSelectedId] = useState(''); const [versions, setVersions] = useState<JourneyBlueprintVersionSummary[]>([]); const [version, setVersion] = useState<JourneyBlueprintVersion | null>(null); const [analysis, setAnalysis] = useState<JourneyBlueprintAnalysis | null>(null); const [draft, setDraft] = useState<Draft | null>(null); const [comparison, setComparison] = useState<JourneyBlueprintComparison | null>(null);
  const [loading, setLoading] = useState(true); const [detailLoading, setDetailLoading] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [activeSection, setActiveSection] = useState('blueprint');
  const selected = blueprints.find((blueprint) => blueprint.id === selectedId) || null;
  const loadIndex = useCallback(async () => { if (!enabled) return; setLoading(true); setError(''); try { const [nextBlueprints, nextResources, mapIndex, portfolioIndex] = await Promise.all([listJourneyServiceBlueprints(true), listJourneyBlueprintResources(true), listJourneyMaps(), portfolioEnabled ? listJourneyPortfolioItems({ limit: 100, sort: 'updated' }) : Promise.resolve({ items: [] })]); setBlueprints(nextBlueprints); setResources(nextResources); setJourneys(mapIndex.journeyMaps); setPortfolioItems(portfolioIndex.items); setSelectedId((current) => nextBlueprints.some((item) => item.id === current) ? current : nextBlueprints[0]?.id || ''); } catch (reason) { setError(errorMessage(reason, 'Service blueprints could not be loaded.')); } finally { setLoading(false); } }, [enabled, portfolioEnabled]);
  useEffect(() => { void loadIndex(); }, [loadIndex]);
  const loadVersion = useCallback(async (versionId: string) => { setDetailLoading(true); setError(''); try { const [nextVersion, nextAnalysis] = await Promise.all([readJourneyServiceBlueprintVersion(versionId), analyseJourneyServiceBlueprint(versionId)]); setVersion(nextVersion); setAnalysis(nextAnalysis); setDraft({ journeyVersionId: nextVersion.journeyVersionId, state: nextVersion.state, changeReason: '', stages: nextVersion.stages, elements: nextVersion.elements, relationships: nextVersion.relationships, portfolioLinks: nextVersion.portfolioLinks || [] }); } catch (reason) { setError(errorMessage(reason, 'Blueprint version could not be loaded.')); setVersion(null); setAnalysis(null); } finally { setDetailLoading(false); } }, []);
  useEffect(() => { if (!selectedId) { setVersions([]); setVersion(null); setDraft(null); return; } let active = true; setDetailLoading(true); void listJourneyServiceBlueprintVersions(selectedId).then((next) => { if (!active) return; setVersions(next); const selectedBlueprint = blueprints.find((item) => item.id === selectedId); const preferred = next.find((item) => item.id === selectedBlueprint?.currentVersionId) || next[0]; if (preferred) return loadVersion(preferred.id); setVersion(null); setAnalysis(null); setDraft(null); }).catch((reason) => active && setError(errorMessage(reason, 'Blueprint history could not be loaded.'))).finally(() => active && setDetailLoading(false)); return () => { active = false; }; }, [blueprints, loadVersion, selectedId]);
  async function act(action: () => Promise<void>) { setBusy(true); setError(''); try { await action(); } catch (reason) { setError(errorMessage(reason, 'The blueprint change could not be saved.')); } finally { setBusy(false); } }
  async function startDraft() { if (!selected) return; await act(async () => { const map = await readJourneyMap(selected.journeyDefinitionId); setDraft({ journeyVersionId: map.version.id, state: 'current', changeReason: '', stages: map.stages.map((stage) => ({ stageKey: stage.stageKey, name: stage.name, ordinal: stage.ordinal })), elements: [], relationships: [], portfolioLinks: [] }); }); }
  async function saveDraft() { if (!selected || !draft) return; await act(async () => { const created = await createJourneyServiceBlueprintVersion(selected.id, draft); await loadIndex(); await loadVersion(created.version.versionId || ''); }); }
  async function downloadExport(format: 'json' | 'csv') {
    if (!version?.versionId) return;
    await act(async () => {
      const artifact = await downloadJourneyServiceBlueprintVersion(version.versionId || '', format);
      const url = URL.createObjectURL(artifact.blob);
      const anchor = document.createElement('a');
      anchor.href = url; anchor.download = artifact.filename; anchor.click();
      URL.revokeObjectURL(url);
    });
  }
  if (!enabled) return null;
  if (loading) return <div className="flex min-h-48 items-center justify-center gap-2 text-sm text-muted-foreground"><LoaderCircle className="h-4 w-4 animate-spin" />Loading service blueprints…</div>;
  return <div className="min-w-0 space-y-5" data-testid="journey-service-blueprint-workspace">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">Service blueprints</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Author operational delivery across customer, frontstage, backstage, system, and control lanes.</p></div><Button variant="outline" disabled={busy} onClick={() => void loadIndex()}><RefreshCw className="h-4 w-4" />Refresh</Button></header>
    {!canManage && <div className="border bg-muted/40 px-4 py-3 text-sm">You have read-only access. Space owners and administrators can author and review blueprints.</div>}
    {error && <div role="alert" className="border border-destructive/40 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}
    <JourneyWorkspaceSavedViewBar surface="service_blueprint" configuration={{
      version: 1, blueprintId: selectedId || null,
      versionMode: comparison ? 'comparison' : (draft?.state || 'current'),
      selectedSection: activeSection === 'analysis' || activeSection === 'history' || activeSection === 'measurements'
        ? activeSection : 'design',
      lifecycles: ['draft', 'in_review', 'approved', 'retired']
    }} onApply={(configuration) => {
      const saved = configuration as JourneyBlueprintViewConfiguration;
      if (saved.blueprintId && blueprints.some((blueprint) => blueprint.id === saved.blueprintId)) setSelectedId(saved.blueprintId);
      setActiveSection(saved.selectedSection === 'design' ? 'blueprint' : saved.selectedSection);
    }} />
    <section className="grid min-w-0 gap-5 lg:grid-cols-[280px_minmax(0,1fr)]">
      <aside className="min-w-0 border"><div className="border-b px-4 py-3"><h2 className="text-sm font-semibold">Blueprints</h2></div><div className="max-h-80 overflow-y-auto p-2">{blueprints.map((blueprint) => <button type="button" aria-current={selectedId === blueprint.id ? 'true' : undefined} className="w-full border-l-2 border-transparent px-3 py-2 text-left hover:bg-muted aria-[current=true]:border-primary aria-[current=true]:bg-muted" key={blueprint.id} onClick={() => setSelectedId(blueprint.id)}><span className="block truncate text-sm font-medium">{blueprint.name}</span><span className="mt-0.5 block text-xs text-muted-foreground">{titleCase(blueprint.lifecycle)}</span></button>)}{blueprints.length === 0 && <p className="p-3 text-sm text-muted-foreground">No service blueprints have been created.</p>}</div></aside>
      <div className="min-w-0">{canManage && <CreateBlueprintForm journeys={journeys} busy={busy} onCreate={(input) => act(async () => { const created = await createJourneyServiceBlueprint(input); await loadIndex(); setSelectedId(created.id); })} />}{selected && <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border px-4 py-3"><div><h2 className="font-semibold">{selected.name}</h2><p className="text-xs text-muted-foreground">Revision {selected.revision} · {titleCase(selected.lifecycle)}</p></div><div className="flex flex-wrap items-center gap-2">{canManage && <select aria-label="Blueprint lifecycle" className="h-9 rounded-md border bg-background px-2 text-sm" value={selected.lifecycle} disabled={busy} onChange={(event) => void act(async () => { await updateJourneyServiceBlueprint(selected, { lifecycle: event.target.value as JourneyBlueprint['lifecycle'] }); await loadIndex(); })}>{journeyBlueprintLifecycles.map((lifecycle) => <option key={lifecycle}>{lifecycle}</option>)}</select>}<select aria-label="Blueprint version" className="h-9 max-w-52 rounded-md border bg-background px-2 text-sm" value={version?.versionId || ''} disabled={detailLoading} onChange={(event) => void loadVersion(event.target.value)}><option value="">No version</option>{versions.map((item) => <option value={item.id} key={item.id}>v{item.version_number} · {titleCase(item.blueprint_state)}</option>)}</select>{exportsEnabled && version?.versionId && <><Button size="sm" variant="outline" disabled={busy} onClick={() => void downloadExport('json')}><Download className="h-4 w-4" />JSON</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => void downloadExport('csv')}><Download className="h-4 w-4" />CSV</Button></>}{canManage && <Button size="sm" variant="outline" onClick={() => void startDraft()}>New version</Button>}</div></div>}</div>
    </section>
    {detailLoading && <div className="flex min-h-32 items-center justify-center gap-2 text-sm text-muted-foreground"><LoaderCircle className="h-4 w-4 animate-spin" />Loading blueprint version…</div>}
    {!detailLoading && selected && !draft && <div className="border p-6 text-sm text-muted-foreground">This blueprint has no version yet.{canManage ? ' Create its first version from the linked journey map.' : ''}</div>}
    {!detailLoading && draft && <Tabs value={activeSection} onValueChange={setActiveSection} className="min-w-0"><div className="max-w-full overflow-x-auto"><TabsList className="w-max min-w-full justify-start"><TabsTrigger value="blueprint">Blueprint</TabsTrigger><TabsTrigger value="elements">Elements</TabsTrigger><TabsTrigger value="relationships">Relationships</TabsTrigger><TabsTrigger value="portfolio">Portfolio causality</TabsTrigger><TabsTrigger value="analysis">Analysis</TabsTrigger>{metricsEnabled&&version?.versionId&&<TabsTrigger value="measurements">Measurements</TabsTrigger>}<TabsTrigger value="resources">Resources</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList></div>
      <TabsContent value="blueprint" className="mt-4 min-w-0"><div className="mb-4 flex flex-wrap items-end gap-3">{canManage && <><div className="grid gap-1.5"><Label htmlFor="blueprint-state">Version state</Label><select id="blueprint-state" className="h-9 rounded-md border bg-background px-2 text-sm" value={draft.state} onChange={(event) => setDraft({ ...draft, state: event.target.value as Draft['state'] })}>{journeyBlueprintStates.map((state) => <option key={state}>{state}</option>)}</select></div><div className="grid min-w-64 flex-1 gap-1.5"><Label htmlFor="blueprint-change-reason">Change reason</Label><Input id="blueprint-change-reason" maxLength={1000} value={draft.changeReason} onChange={(event) => setDraft({ ...draft, changeReason: event.target.value })} /></div><Button disabled={busy || draft.stages.length === 0} onClick={() => void saveDraft()}><Save className="h-4 w-4" />Save new version</Button></>}{version && canManage && <div className="ml-auto grid gap-1.5"><Label htmlFor="blueprint-review-state">Review state</Label><select id="blueprint-review-state" className="h-9 rounded-md border bg-background px-2 text-sm" value={version.reviewState || 'draft'} disabled={busy} onChange={(event) => void act(async () => { const next = await reviewJourneyServiceBlueprintVersion(version, event.target.value as typeof journeyBlueprintReviewStates[number]); setVersion(next); const nextVersions = await listJourneyServiceBlueprintVersions(selectedId); setVersions(nextVersions); })}>{journeyBlueprintReviewStates.map((state) => <option key={state}>{state}</option>)}</select></div>}</div><BlueprintGrid draft={draft} onSelect={() => undefined} /></TabsContent>
      <TabsContent value="elements" className="mt-4 min-w-0"><ElementEditor draft={draft} resources={resources} canManage={canManage} onChange={setDraft} /></TabsContent>
      <TabsContent value="relationships" className="mt-4 min-w-0"><RelationshipEditor draft={draft} canManage={canManage} onChange={setDraft} /></TabsContent>
      <TabsContent value="portfolio" className="mt-4 min-w-0"><PortfolioCausalityEditor draft={draft} items={portfolioItems} canManage={canManage && portfolioEnabled} onChange={setDraft} />{!portfolioEnabled && <p className="mt-3 border px-4 py-3 text-sm text-muted-foreground">Portfolio linking is unavailable on this plan. Existing pinned links remain visible.</p>}</TabsContent>
      <TabsContent value="analysis" className="mt-4 min-w-0">{version ? <AnalysisPanel analysis={analysis} version={version} canManage={canManage} onReviewGap={(gapId, state) => act(async () => { await reviewJourneyBlueprintGap(gapId, state); await loadVersion(version.versionId || ''); })} /> : <p className="border p-4 text-sm text-muted-foreground">Save this draft before analysis and persisted gap review are available.</p>}</TabsContent>
      {metricsEnabled&&version?.versionId&&<TabsContent value="measurements" className="mt-4 min-w-0"><JourneyBlueprintMeasurementPanel version={version} canManage={canManage}/></TabsContent>}
      <TabsContent value="resources" className="mt-4 min-w-0"><ResourceCatalogue resources={resources} canManage={canManage} busy={busy} onCreate={(input) => act(async () => { await createJourneyBlueprintResource(input); setResources(await listJourneyBlueprintResources(true)); })} onToggle={(resource) => act(async () => { await updateJourneyBlueprintResource(resource, { lifecycle: resource.lifecycle === 'active' ? 'retired' : 'active' }); setResources(await listJourneyBlueprintResources(true)); })} /></TabsContent>
      <TabsContent value="history" className="mt-4 min-w-0"><HistoryPanel versions={versions} comparison={comparison} busy={busy} onCompare={(from, to) => act(async () => setComparison(await compareJourneyServiceBlueprintVersions(from, to)))} /></TabsContent>
    </Tabs>}
  </div>;
}

function CreateBlueprintForm({ journeys, busy, onCreate }: { journeys: JourneyDefinitionSummary[]; busy: boolean; onCreate: (input: { journeyDefinitionId: string; name: string }) => Promise<void> }) {
  const [journeyDefinitionId, setJourneyDefinitionId] = useState(''); const [name, setName] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); await onCreate({ journeyDefinitionId, name: name.trim() }); setName(''); }
  return <form className="border p-4" onSubmit={(event) => void submit(event)}><h2 className="text-sm font-semibold">Create blueprint</h2><div className="mt-3 grid gap-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]"><div className="grid gap-1.5"><Label htmlFor="blueprint-journey">Journey</Label><select id="blueprint-journey" required className="h-9 min-w-0 rounded-md border bg-background px-2 text-sm" value={journeyDefinitionId} onChange={(event) => setJourneyDefinitionId(event.target.value)}><option value="">Choose journey</option>{journeys.map((journey) => <option value={journey.id} key={journey.id}>{journey.name}</option>)}</select></div><div className="grid gap-1.5"><Label htmlFor="blueprint-name">Name</Label><Input id="blueprint-name" required maxLength={200} value={name} onChange={(event) => setName(event.target.value)} /></div><Button className="self-end" type="submit" disabled={busy || !journeyDefinitionId || !name.trim()}><Plus className="h-4 w-4" />Create</Button></div></form>;
}

function HistoryPanel({ versions, comparison, busy, onCompare }: { versions: JourneyBlueprintVersionSummary[]; comparison: JourneyBlueprintComparison | null; busy: boolean; onCompare: (from: string, to: string) => Promise<void> }) {
  const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const changedCount = comparison ? comparison.changed.length + comparison.addedElementIds.length + comparison.removedElementIds.length : 0;
  return <div className="grid min-w-0 gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="overflow-x-auto border"><table className="w-full min-w-[620px] text-left text-sm"><caption className="sr-only">Current and future service blueprint version history</caption><thead className="border-b bg-muted/50"><tr><th className="px-3 py-2">Version</th><th className="px-3 py-2">State</th><th className="px-3 py-2">Review</th><th className="px-3 py-2">Change reason</th><th className="px-3 py-2">Created</th></tr></thead><tbody>{versions.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="px-3 py-2 font-medium">v{item.version_number}</td><td className="px-3 py-2">{titleCase(item.blueprint_state)}</td><td className="px-3 py-2">{titleCase(item.review_state)}</td><td className="px-3 py-2 text-muted-foreground">{item.change_reason || '—'}</td><td className="px-3 py-2">{new Date(item.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{versions.length === 0 && <p className="p-4 text-sm text-muted-foreground">No version history is available.</p>}</div><section className="h-fit border p-4" aria-labelledby="comparison-heading"><h2 id="comparison-heading" className="text-sm font-semibold">Compare versions</h2><div className="mt-3 grid gap-3">{[['comparison-from', 'From', from, setFrom], ['comparison-to', 'To', to, setTo]].map(([id, label, value, setter]) => <div className="grid gap-1.5" key={id as string}><Label htmlFor={id as string}>{label as string}</Label><select id={id as string} className="h-9 rounded-md border bg-background px-2 text-sm" value={value as string} onChange={(event) => (setter as (value: string) => void)(event.target.value)}><option value="">Choose version</option>{versions.map((item) => <option value={item.id} key={item.id}>v{item.version_number} · {item.blueprint_state}</option>)}</select></div>)}<Button disabled={busy || !from || !to || from === to} onClick={() => void onCompare(from, to)}><GitCompare className="h-4 w-4" />Compare</Button>{comparison && <div className="border-t pt-3 text-sm"><p className="font-medium">{changedCount} element changes</p><p className="mt-1 text-muted-foreground">{comparison.addedStageKeys.length} stages added · {comparison.removedStageKeys.length} removed</p><p className="mt-1 text-muted-foreground">{comparison.addedRelationshipIds.length} relationships added · {comparison.removedRelationshipIds.length} removed</p></div>}</div></section></div>;
}
