import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { AlertTriangle, LoaderCircle, Play, Plus, RefreshCw, Upload } from 'lucide-react';
import { useAuthSession, useSessionFeature } from '@/lib/authSessionContext';
import { ApiError } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  createJourneyConnector, journeyConnectorKinds, listJourneyConnectorAudit, listJourneyConnectorReceipts, listJourneyConnectors,
  readJourneyConnectorImport, setJourneyConnectorState, startJourneyConnectorImport, submitJourneyConnectorPage,
  type JourneyConnector, type JourneyConnectorAudit, type JourneyConnectorKind, type JourneyConnectorPageItem,
  type JourneyConnectorReceipt, type JourneyConnectorRun
} from '@/lib/journeyConnectors';

const selectClass = 'h-9 min-w-0 rounded-md border bg-background px-2 text-sm';
const textareaClass = 'min-h-36 w-full rounded-md border bg-background px-3 py-2 font-mono text-xs focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-50';
const readable = (value: string) => value.toLowerCase().replace(/[_.]/gu, ' ').replace(/\b\w/gu, (letter) => letter.toUpperCase());
const errorText = (reason: unknown, fallback: string) => reason instanceof Error ? reason.message : fallback;
const parseItems = (value: string) => { try { const parsed = JSON.parse(value); if (!Array.isArray(parsed)) throw new Error(); return parsed as JourneyConnectorPageItem[]; }
  catch { throw new Error('Page items must be a valid JSON array.'); } };

function CreateConnectorForm({ busy, onCreate }: { busy: boolean; onCreate: (input: { kind: JourneyConnectorKind; name: string; maximumAttempts: number; baseRetrySeconds: number }) => Promise<void> }) {
  const [kind, setKind] = useState<JourneyConnectorKind>('csv_upload'); const [name, setName] = useState('');
  const [maximumAttempts, setMaximumAttempts] = useState(5); const [baseRetrySeconds, setBaseRetrySeconds] = useState(5);
  async function submit(event: FormEvent) { event.preventDefault(); await onCreate({ kind, name: name.trim(), maximumAttempts, baseRetrySeconds }); setName(''); }
  return <form className="border p-4" onSubmit={(event) => void submit(event)}><h2 className="text-sm font-semibold">Create approved staging connector</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-[220px_minmax(220px,1fr)_130px_150px_auto]"><div className="grid gap-1.5"><Label htmlFor="connector-kind">Staging source</Label><select id="connector-kind" className={selectClass} value={kind} onChange={(event) => setKind(event.target.value as JourneyConnectorKind)}>{journeyConnectorKinds.map((item) => <option value={item} key={item}>{readable(item)}</option>)}</select></div><div className="grid gap-1.5"><Label htmlFor="connector-name">Name</Label><Input id="connector-name" required maxLength={160} value={name} onChange={(event) => setName(event.target.value)} /></div><div className="grid gap-1.5"><Label htmlFor="connector-attempts">Max attempts</Label><Input id="connector-attempts" type="number" min={1} max={10} value={maximumAttempts} onChange={(event) => setMaximumAttempts(Number(event.target.value))} /></div><div className="grid gap-1.5"><Label htmlFor="connector-retry">Base retry seconds</Label><Input id="connector-retry" type="number" min={1} max={300} value={baseRetrySeconds} onChange={(event) => setBaseRetrySeconds(Number(event.target.value))} /></div><Button className="self-end" type="submit" disabled={busy || !name.trim()}><Plus className="h-4 w-4" />Create</Button></div></form>;
}

function RunSummary({ run }: { run: JourneyConnectorRun }) { return <div className="grid gap-3 border p-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted-foreground">State</p><p className="mt-1 text-sm font-medium">{readable(run.state)}</p></div><div><p className="text-xs text-muted-foreground">Checkpoint</p><p className="mt-1 text-sm font-medium">Revision {run.checkpointRevision}</p></div><div><p className="text-xs text-muted-foreground">Page outcomes</p><p className="mt-1 text-sm font-medium">{run.acceptedCount} accepted · {run.rejectedCount} rejected</p></div><div><p className="text-xs text-muted-foreground">Tombstones</p><p className="mt-1 text-sm font-medium">{run.tombstoneCount}</p></div>{run.state === 'retry_wait' && <p className="text-sm sm:col-span-2 lg:col-span-4">Retry attempt {run.attemptCount}. Eligible again {run.retryAt ? new Date(run.retryAt).toLocaleString() : 'after the configured wait'}.</p>}{run.lastErrorCode && <p className="text-sm text-destructive sm:col-span-2 lg:col-span-4">Last provider outcome: {readable(run.lastErrorCode)}</p>}</div>; }

function ImportWorkspace({ connector, run, receipts, canManage, busy, onStart, onLoad, onSubmit, onMore }: { connector: JourneyConnector; run: JourneyConnectorRun | null;
  receipts: JourneyConnectorReceipt[]; canManage: boolean; busy: boolean; onStart: () => Promise<void>; onLoad: (id: string) => Promise<void>;
  onSubmit: (input: Parameters<typeof submitJourneyConnectorPage>[1]) => Promise<void>; onMore: () => Promise<void> }) {
  const [runId, setRunId] = useState(''); const [outcome, setOutcome] = useState<'ok' | 'rate_limited' | 'transient_failure'>('ok');
  const [nextCursor, setNextCursor] = useState(''); const [retryAfter, setRetryAfter] = useState(30);
  const [items, setItems] = useState('[\n  {\n    "externalId": "record-1",\n    "operation": "upsert",\n    "checksum": "replace-with-sha256",\n    "occurredAt": "2026-08-07T10:00:00.000Z",\n    "payload": {}\n  }\n]');
  async function submit(event: FormEvent) { event.preventDefault(); if (!run) return; const failed = outcome !== 'ok'; await onSubmit({
    expectedCheckpointRevision: run.checkpointRevision, cursor: run.expectedCursor, nextCursor: failed ? run.expectedCursor : nextCursor.trim() || null,
    providerOutcome: outcome, ...(failed ? { retryAfterSeconds: retryAfter } : {}), items: failed ? [] : parseItems(items) }); }
  return <div className="space-y-4"><div className="grid gap-3 border p-4 lg:grid-cols-[minmax(0,1fr)_auto]"><div><h2 className="text-sm font-semibold">Import checkpoint</h2><p className="mt-1 text-xs text-muted-foreground">Start a run for this staging connector or open a known run ID. Cursors are opaque and must match the persisted checkpoint exactly.</p><div className="mt-3 flex max-w-xl gap-2"><Input aria-label="Import run ID" placeholder="Import run ID" value={runId} onChange={(event) => setRunId(event.target.value)} /><Button variant="outline" disabled={busy || !runId.trim()} onClick={() => void onLoad(runId.trim())}>Load run</Button></div></div>{canManage && <Button disabled={busy || connector.state !== 'active'} onClick={() => void onStart()}><Play className="h-4 w-4" />Start import</Button>}</div>
    {run && <><RunSummary run={run} />{canManage && ['open', 'retry_wait'].includes(run.state) && <form className="border p-4" onSubmit={(event) => void submit(event)}><h2 className="text-sm font-semibold">Submit staged page</h2><p className="mt-1 text-xs text-muted-foreground">A successful page may be partially accepted. Invalid items receive immutable rejection receipts while valid items commit. Deletes always create irreversible tombstones.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="grid gap-1.5"><Label htmlFor="page-outcome">Staging read outcome</Label><select id="page-outcome" className={selectClass} value={outcome} onChange={(event) => setOutcome(event.target.value as typeof outcome)}><option value="ok">OK</option><option value="rate_limited">Rate limited</option><option value="transient_failure">Transient failure</option></select></div><div className="grid gap-1.5"><Label htmlFor="page-current-cursor">Current cursor</Label><Input id="page-current-cursor" readOnly value={run.expectedCursor || ''} placeholder="Initial page" /></div>{outcome === 'ok' ? <div className="grid gap-1.5"><Label htmlFor="page-next-cursor">Next cursor</Label><Input id="page-next-cursor" value={nextCursor} onChange={(event) => setNextCursor(event.target.value)} placeholder="Blank completes import" /></div> : <div className="grid gap-1.5"><Label htmlFor="page-retry-after">Retry after seconds</Label><Input id="page-retry-after" type="number" min={1} max={86400} value={retryAfter} onChange={(event) => setRetryAfter(Number(event.target.value))} /></div>}</div><div className="mt-3 grid gap-1.5"><Label htmlFor="page-items">Staged items (JSON)</Label><textarea id="page-items" className={textareaClass} disabled={outcome !== 'ok'} value={outcome === 'ok' ? items : '[]'} onChange={(event) => setItems(event.target.value)} /></div><div className="mt-3 flex justify-end"><Button type="submit" disabled={busy}><Upload className="h-4 w-4" />Submit page</Button></div></form>}
      <ReceiptTable receipts={receipts} onMore={onMore} busy={busy} /></>}
    {!run && <p className="border p-4 text-sm text-muted-foreground">No import run is selected. Members can inspect a run when given its content-safe run ID.</p>}</div>;
}

function ReceiptTable({ receipts, onMore, busy }: { receipts: JourneyConnectorReceipt[]; onMore: () => Promise<void>; busy: boolean }) { return <section className="border"><div className="flex items-center justify-between gap-3 border-b px-4 py-3"><div><h2 className="text-sm font-semibold">Item receipts</h2><p className="mt-1 text-xs text-muted-foreground">External identifiers are shown only as SHA-256 hashes. Payloads are never included.</p></div><Button size="sm" variant="outline" disabled={busy} onClick={() => void onMore()}>Load more</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="px-3 py-2">Created</th><th className="px-3 py-2">Identifier hash</th><th className="px-3 py-2">Operation</th><th className="px-3 py-2">Outcome</th><th className="px-3 py-2">Code</th><th className="px-3 py-2">Checkpoint</th></tr></thead><tbody>{receipts.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="px-3 py-2">{new Date(item.createdAt).toLocaleString()}</td><td className="px-3 py-2 font-mono text-xs" title={item.externalIdSha256}>{item.externalIdSha256.slice(0, 16)}…</td><td className="px-3 py-2">{readable(item.operation)}</td><td className="px-3 py-2">{readable(item.outcome)}</td><td className="px-3 py-2">{readable(item.code)}</td><td className="px-3 py-2">{item.checkpointRevision}</td></tr>)}</tbody></table></div>{receipts.length === 0 && <p className="p-4 text-sm text-muted-foreground">No item receipts have been recorded for this run.</p>}</section>; }

function AuditTable({ events }: { events: JourneyConnectorAudit[] }) { return <section className="border"><div className="border-b px-4 py-3"><h2 className="text-sm font-semibold">Connector audit history</h2><p className="mt-1 text-xs text-muted-foreground">Audit details are content-safe: no payload, cursor, external identifier, secret, or token fields are stored.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="px-3 py-2">Created</th><th className="px-3 py-2">Action</th><th className="px-3 py-2">Target</th><th className="px-3 py-2">Safe detail</th><th className="px-3 py-2">Evidence hash</th></tr></thead><tbody>{events.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="px-3 py-2">{new Date(item.createdAt).toLocaleString()}</td><td className="px-3 py-2">{readable(item.action)}</td><td className="px-3 py-2">{readable(item.targetType)}</td><td className="px-3 py-2">{Object.entries(item.detail).map(([key, value]) => `${readable(key)}: ${String(value)}`).join(' · ') || '—'}</td><td className="px-3 py-2 font-mono text-xs" title={item.detailSha256}>{item.detailSha256.slice(0, 16)}…</td></tr>)}</tbody></table></div>{events.length === 0 && <p className="p-4 text-sm text-muted-foreground">No connector audit events have been recorded.</p>}</section>; }

export function JourneyConnectorsPage() {
  const enabled = useSessionFeature('journeyConnectors'); const session = useAuthSession(); const canManage = Boolean(session?.activeSpace && session.activeSpace.role !== 'member');
  const [connectors, setConnectors] = useState<JourneyConnector[]>([]); const [selectedId, setSelectedId] = useState(''); const selected = useMemo(() => connectors.find((item) => item.id === selectedId) || null, [connectors, selectedId]);
  const [run, setRun] = useState<JourneyConnectorRun | null>(null); const [receipts, setReceipts] = useState<JourneyConnectorReceipt[]>([]); const [receiptCursor, setReceiptCursor] = useState<string | null>(null);
  const [audit, setAudit] = useState<JourneyConnectorAudit[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [conflict, setConflict] = useState('');
  const load = useCallback(async () => { if (!enabled) return; setLoading(true); setError(''); try { const [next, events] = await Promise.all([listJourneyConnectors(), listJourneyConnectorAudit()]); setConnectors(next); setAudit(events); setSelectedId((current) => next.some((item) => item.id === current) ? current : next[0]?.id || ''); } catch (reason) { setError(errorText(reason, 'Journey connectors could not be loaded.')); } finally { setLoading(false); } }, [enabled]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { setRun(null); setReceipts([]); setReceiptCursor(null); }, [selectedId]);
  async function loadRun(id: string) { const next = await readJourneyConnectorImport(id); if (selected && next.connectorId !== selected.id) throw new Error('This import belongs to a different connector.'); const page = await listJourneyConnectorReceipts(id); setRun(next); setReceipts(page.items); setReceiptCursor(page.nextCursor); }
  async function act(action: () => Promise<void>) { setBusy(true); setError(''); setConflict(''); try { await action(); } catch (reason) { if (reason instanceof ApiError && reason.status === 409) { setConflict('Connector or checkpoint changed elsewhere. Latest state has been reloaded; review it before retrying.'); await load(); if (run) await loadRun(run.id).catch(() => undefined); } else setError(errorText(reason, 'The connector change could not be completed.')); } finally { setBusy(false); } }
  if (!enabled) return null; if (loading) return <div className="flex min-h-48 items-center justify-center gap-2 text-sm text-muted-foreground"><LoaderCircle className="h-4 w-4 animate-spin" />Loading journey connectors…</div>;
  return <div className="min-w-0 space-y-5" data-testid="journey-connectors-workspace"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">Journey connectors</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Import staged journey records through checkpointed, receipt-backed connectors.</p></div><Button variant="outline" disabled={busy} onClick={() => void load()}><RefreshCw className="h-4 w-4" />Refresh</Button></header>
    <div className="border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-950"><div className="flex gap-2"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /><div><strong>No live provider connections or credentials.</strong> This release accepts only approved local CSV/JSONL staging and approved object-store staging. It does not collect, store, or use provider API keys, OAuth tokens, or direct CRM/CDP connections.</div></div></div>
    {!canManage && <div className="border bg-muted/40 px-4 py-3 text-sm">Read-only: connector creation, state changes, import starts, and page submissions are disabled for members.</div>}
    {error && <div role="alert" className="border border-destructive/40 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}{conflict && <div role="alert" className="border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-950">{conflict}</div>}
    {canManage && <CreateConnectorForm busy={busy} onCreate={(input) => act(async () => { const created = await createJourneyConnector(input); await load(); setSelectedId(created.id); })} />}
    <section className="grid min-w-0 gap-5 lg:grid-cols-[280px_minmax(0,1fr)]"><aside className="min-w-0 border"><div className="border-b px-4 py-3"><h2 className="text-sm font-semibold">Approved connectors</h2></div><div className="max-h-[520px] overflow-y-auto p-2">{connectors.map((item) => <button type="button" className="w-full border-l-2 border-transparent px-3 py-2 text-left hover:bg-muted aria-[current=true]:border-primary aria-[current=true]:bg-muted" aria-current={selectedId === item.id ? 'true' : undefined} onClick={() => setSelectedId(item.id)} key={item.id}><span className="block truncate text-sm font-medium">{item.name}</span><span className="mt-0.5 block text-xs text-muted-foreground">{readable(item.kind)} · {readable(item.state)}</span></button>)}{connectors.length === 0 && <p className="p-3 text-sm text-muted-foreground">No approved staging connectors have been created.</p>}</div></aside>
      <div className="min-w-0">{!selected && connectors.length === 0 && <div className="border p-6 text-sm text-muted-foreground">Create a connector for an approved staged source before starting an import.</div>}{selected && <><div className="mb-4 flex flex-wrap items-center justify-between gap-3 border px-4 py-3"><div><h2 className="font-semibold">{selected.name}</h2><p className="mt-0.5 text-xs text-muted-foreground">{readable(selected.kind)} · revision {selected.revision} · tombstone deletion</p></div>{canManage && <Button size="sm" variant="outline" disabled={busy} onClick={() => void act(async () => { const updated = await setJourneyConnectorState(selected, selected.state === 'active' ? 'disabled' : 'active'); setConnectors((current) => current.map((item) => item.id === updated.id ? updated : item)); })}>{selected.state === 'active' ? 'Disable connector' : 'Enable connector'}</Button>}</div>
        <Tabs defaultValue="import"><div className="max-w-full overflow-x-auto"><TabsList className="w-max min-w-full justify-start" role="tablist"><TabsTrigger value="import">Import</TabsTrigger><TabsTrigger value="policy">Retry and deletion policy</TabsTrigger><TabsTrigger value="audit">Audit history</TabsTrigger></TabsList></div><TabsContent value="import"><ImportWorkspace connector={selected} run={run} receipts={receipts} canManage={canManage} busy={busy} onStart={() => act(async () => { const next = await startJourneyConnectorImport(selected.id); setRun(next); setReceipts([]); setReceiptCursor(null); })} onLoad={(id) => act(() => loadRun(id))} onSubmit={(input) => act(async () => { if (!run) return; const result = await submitJourneyConnectorPage(run.id, input); setRun(result.run); setReceipts((current) => [...current, ...result.receipts]); const events = await listJourneyConnectorAudit(); setAudit(events); })} onMore={() => act(async () => { if (!run) return; const page = await listJourneyConnectorReceipts(run.id, receiptCursor || undefined); setReceipts((current) => [...current, ...page.items.filter((item) => !current.some((old) => old.id === item.id))]); setReceiptCursor(page.nextCursor); })} /></TabsContent>
          <TabsContent value="policy"><section className="border p-4"><h2 className="text-sm font-semibold">Bounded retry and deletion policy</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-muted-foreground">Maximum attempts</dt><dd className="mt-1 font-medium">{selected.maximumAttempts}</dd></div><div><dt className="text-muted-foreground">Base retry</dt><dd className="mt-1 font-medium">{selected.baseRetrySeconds} seconds, capped at 1 hour</dd></div><div><dt className="text-muted-foreground">Deletion</dt><dd className="mt-1 font-medium">Tombstone only</dd></div></dl><p className="mt-4 text-sm text-muted-foreground">Successful pages commit valid items and reject invalid items independently. Tombstoned identifiers cannot be resurrected by later upserts. Rate limits and transient failures retain the cursor and stop permanently at the attempt limit.</p></section></TabsContent>
          <TabsContent value="audit"><AuditTable events={audit} /></TabsContent></Tabs></>}</div></section>
  </div>;
}
