import { ArrowLeft } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link } from '@/lib/router';

const effectiveDate = '29 July 2026';

function LegalShell({ title, intro, children }: { title: string; intro: string; children: ReactNode }) {
  return <main className="min-h-screen bg-background"><header className="border-b bg-card"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-5"><Link to="/" className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-md bg-primary text-sm font-bold text-primary-foreground">S</span><span className="text-sm font-semibold">Seemplify Experience</span></Link><Link to="/login" className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back to sign in</Link></div></header><article className="mx-auto max-w-3xl px-5 py-12"><p className="text-sm text-muted-foreground">Effective date: {effectiveDate}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground">{intro}</p><div className="legal-copy mt-10 space-y-9">{children}</div><div className="mt-12 flex flex-wrap gap-5 border-t pt-6 text-sm"><Link className="underline underline-offset-4" to="/legal/terms">Terms</Link><Link className="underline underline-offset-4" to="/legal/privacy">Privacy</Link><a className="underline underline-offset-4" href="mailto:support@seemplify.com">support@seemplify.com</a></div></article></main>;
}

const Section = ({ title, children }: { title: string; children: ReactNode }) => <section><h2 className="text-lg font-semibold">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-muted-foreground">{children}</div></section>;

export function LegalPage({ kind }: { kind: 'terms' | 'privacy' }) {
  if (kind === 'terms') return <LegalShell title="Terms of Service" intro="These terms govern access to Seemplify Experience, including surveys, campaigns, X social listening, and AI-assisted research tools.">
    <Section title="1. Agreement and accounts"><p>By creating an account or using the service, you agree to these terms. You are responsible for accurate account information, secure credentials, activity under your account, and ensuring that your team members have appropriate authority.</p></Section>
    <Section title="2. Permitted use"><p>You may use Seemplify for lawful experience research, survey distribution, service recovery, and social listening. You must have a lawful basis and any required permission to collect, upload, analyse, contact, or retain personal data.</p><p>You may not use the service to harass people, evade platform controls, send unlawful or deceptive messages, scrape data outside supported APIs, infringe rights, introduce malicious content, or attempt to access another user’s credentials or data.</p></Section>
    <Section title="3. X integration"><p>The X connector is read-only. It can retrieve the connected profile, account posts, mentions, and public recent-search results permitted by your X developer app and plan. You remain responsible for your X developer account, API configuration, usage credits, queries, and compliance with X’s terms and developer policies.</p><p>X may change its APIs, limits, pricing, permissions, or availability. Seemplify cannot guarantee uninterrupted access to a third-party service and will show actionable connection, permission, billing, and rate-limit states when available.</p></Section>
    <Section title="4. AI-assisted outputs"><p>Terra-generated summaries, classifications, reports, and recommendations are assistive outputs, not professional advice or guaranteed facts. Review source evidence and exercise human judgment before making employment, legal, financial, safety, or other consequential decisions.</p></Section>
    <Section title="5. Surveys and communications"><p>You are responsible for survey content, recipient lists, consent, unsubscribe handling, sender identity, and compliance with applicable marketing and privacy law. Provider acceptance does not guarantee inbox delivery.</p></Section>
    <Section title="6. Your content and our software"><p>You retain rights in content you provide. You grant Seemplify the limited permission needed to host, process, transmit, and analyse that content to operate the service. Seemplify and its licensors retain rights in the software, design, documentation, and service marks.</p></Section>
    <Section title="7. Suspension and termination"><p>We may limit or suspend access to protect users, the service, third-party platforms, or legal compliance. You may stop using the service and disconnect X at any time. Disconnecting removes usable OAuth access and stops automatic collection. Saved queries, sync history, the account association, and previously collected evidence remain available for audit until they are separately deleted under the controls described in the Privacy Policy.</p></Section>
    <Section title="8. Disclaimers and liability"><p>The service is provided on an “as available” basis to the extent permitted by law. We do not warrant that third-party APIs or AI outputs will always be available, complete, or error-free. To the extent permitted by law, Seemplify is not liable for indirect, incidental, special, consequential, or lost-profit damages arising from use of the service.</p></Section>
    <Section title="9. Changes, governing terms, and contact"><p>We may update these terms as the service or law changes and will revise the effective date. Applicable mandatory local law continues to apply. Questions or legal notices can be sent to <a className="text-foreground underline" href="mailto:support@seemplify.com">support@seemplify.com</a>.</p></Section>
  </LegalShell>;

  return <LegalShell title="Privacy Policy" intro="This policy explains what Seemplify Experience processes, why it is used, and the controls available to workspace users—including when X is connected.">
    <Section title="1. Information we process"><p>Account data includes your name, email address, role, authentication records, and security events. Workspace content can include surveys, responses, campaign contacts, delivery events, journey maps, support tickets, and AI job records.</p><p>When X is connected, we process the authorised X profile, X user ID, username, account posts, mentions, public search results matching saved queries, post metadata, sync history, and API rate-limit information. We also store encrypted developer-app and account access credentials.</p></Section>
    <Section title="2. How information is used"><p>We use information to authenticate users, operate surveys and campaigns, collect and organise permitted X evidence, generate requested Terra analysis, maintain durable queues, prevent abuse, diagnose failures, and provide an auditable service history.</p></Section>
    <Section title="3. X credentials and data"><p>X consumer secrets, bearer tokens, access tokens, and access-token secrets are encrypted at rest with a dedicated local key. They are not returned by the API or displayed after saving. OAuth request tokens are one-time, hashed, short-lived, and bound to the browser that started the connection.</p><p>The X connector requests read access only. Seemplify does not use it to post, like, follow, send direct messages, or change the connected account. Search queries and pagination markers remain server-side.</p></Section>
    <Section title="4. AI processing and service providers"><p>Selected workspace evidence is sent through the configured managed Terra runtime to produce requested analysis. Email delivery may use Brevo. X data is obtained from X’s API. These providers process data under their own terms and privacy commitments; availability and processing locations may differ by provider.</p></Section>
    <Section title="5. Cookies and security"><p>We use an HttpOnly signed session cookie for authentication. X sign-in uses a separate HttpOnly cookie that expires after ten minutes and is restricted to the callback path. We apply access controls, encrypted secret storage, bounded inputs, durable audit records, and transport security, but no system can guarantee absolute security.</p></Section>
    <Section title="6. Retention and deletion"><p>Workspace records remain until deleted by an authorised user or according to an agreed retention schedule. Disconnecting X replaces the usable account credentials and stops automatic collection, while saved queries, sync history, the account association, and collected posts remain available for audit. The Delete X history control removes this account’s post links, deletes post records not retained by another connection, deletes its sync audit records and derived Terra analysis jobs, and turns off automatic sync. A later manual sync may collect public posts again. OAuth handshakes expire after ten minutes and stale records are removed.</p></Section>
    <Section title="7. Your choices and rights"><p>You can disconnect X, pause automatic sync, disable or delete listening queries, and permanently delete collected X post history. Depending on applicable law, you may also request access, correction, export, restriction, objection, or deletion of personal information. Workspace administrators may need to act on requests involving organisation-controlled data.</p></Section>
    <Section title="8. Children, changes, and contact"><p>Seemplify Experience is not directed to children. We may update this policy as features, providers, or legal requirements change and will revise the effective date. Send privacy requests to <a className="text-foreground underline" href="mailto:support@seemplify.com">support@seemplify.com</a>.</p></Section>
  </LegalShell>;
}
