import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { AlertCircle, CheckCircle2, ChevronRight, Download, FileSignature, Loader2, LockKeyhole, PenLine, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { api, json } from '@/lib/api';
import { useParams } from '@/lib/router';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { SignatureCanvas, SigningDocument } from '@/components/esign/SigningDocument';
import type { ESignField, ESignPublicDetail, ESignPublicSession, ESignSignatureValue } from '@/types';

function isComplete(field: ESignField) {
  if (!field.required || field.hasValue === true) return true; if (field.type === 'checkbox') return field.value === true;
  if (typeof field.value === 'object' && field.value) return Boolean((field.value as ESignSignatureValue).value || (field.value as ESignSignatureValue).dataUrl);
  if (Array.isArray(field.value)) return field.value.length > 0; return String(field.value ?? '').trim().length > 0;
}

function initialsFor(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 3).map((part) => part[0]?.toUpperCase()).join('').slice(0, 12); }

function valuePresent(field: ESignField, value: ESignField['value']) {
  if (['name', 'email', 'date_signed'].includes(field.type)) return true;
  if (field.type === 'checkbox') return value === true;
  if (typeof value === 'object' && value && !Array.isArray(value)) return Boolean((value as ESignSignatureValue).value || (value as ESignSignatureValue).dataUrl);
  if (Array.isArray(value)) return value.length > 0;
  return String(value ?? '').trim().length > 0;
}

function PublicFrame({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-background"><header className="flex h-14 items-center border-b bg-card px-4 sm:px-6"><div className="grid h-7 w-7 place-items-center rounded-md bg-primary text-xs font-bold text-primary-foreground">S</div><div className="ml-2 text-sm font-semibold">Seemplify eSignature</div></header>{children}</div>;
}

export function PublicSigningPage() {
  const params = useParams<{ token?: string }>(); const token = params.token || new URLSearchParams(window.location.search).get('token') || ''; const [session, setSession] = useState<ESignPublicSession | null>(null); const [detail, setDetail] = useState<ESignPublicDetail | null>(null);
  const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState(''); const [accessCode, setAccessCode] = useState('');
  const [consentChecked, setConsentChecked] = useState(false); const [signatureField, setSignatureField] = useState<ESignField | null>(null); const [signatureMode, setSignatureMode] = useState<'typed' | 'drawn' | 'uploaded'>('typed'); const [typedSignature, setTypedSignature] = useState(''); const [signatureImage, setSignatureImage] = useState('');
  const [declineOpen, setDeclineOpen] = useState(false); const [declineReason, setDeclineReason] = useState(''); const [completed, setCompleted] = useState(false);
  const [pendingSaves, setPendingSaves] = useState(0); const pendingSavesRef = useRef(0);
  async function loadDetail() { const next = await api<ESignPublicDetail>('/api/public/esign/envelope'); setDetail(next); setSession(next); setCompleted(next.recipient.status === 'completed' || next.envelope.status === 'completed'); }
  useEffect(() => { void (async () => {
    try {
      const next = token
        ? await api<ESignPublicSession>('/api/public/esign/session', json('POST', { token }))
        : await api<ESignPublicSession>('/api/public/esign/session');
      if (token) window.history.replaceState({}, document.title, '/sign');
      setSession(next); if (next.authenticated && (next.consented || next.envelope.status === 'completed')) await loadDetail();
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'This signing link is invalid or no longer available.'); }
    finally { setLoading(false); }
  })(); }, [token]);
  async function authenticate(event: FormEvent) { event.preventDefault(); try { setWorking(true); const next = await api<ESignPublicSession>('/api/public/esign/access-code', json('POST', { code: accessCode })); setSession(next); setAccessCode(''); } catch (reason) { toast.error(reason instanceof Error ? reason.message : 'The access code was not accepted.'); } finally { setWorking(false); } }
  async function consent() { try { setWorking(true); const next = await api<ESignPublicSession>('/api/public/esign/consent', json('POST', { agreed: true })); setSession(next); await loadDetail(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : 'Consent could not be recorded.'); } finally { setWorking(false); } }
  function localField(id: string, value: ESignField['value'], saved = false) { setDetail((current) => current ? { ...current, fields: current.fields.map((field) => field.id === id ? { ...field, value, hasValue: saved ? valuePresent(field, value) : valuePresent(field, value) } : field) } : current); }
  async function saveField(id: string, value: ESignField['value']) {
    pendingSavesRef.current += 1; setPendingSaves(pendingSavesRef.current);
    try { const body = typeof value === 'object' && value && !Array.isArray(value) && 'mode' in value ? { signature: value } : { value }; await api(`/api/public/esign/fields/${id}`, json('PUT', body)); localField(id, value, true); }
    catch (reason) { toast.error(reason instanceof Error ? reason.message : 'This field could not be saved.'); await loadDetail().catch(() => undefined); }
    finally { pendingSavesRef.current = Math.max(0, pendingSavesRef.current - 1); setPendingSaves(pendingSavesRef.current); }
  }
  function openSignature(field: ESignField) { setSignatureField(field); setSignatureMode('typed'); const saved = typeof field.value === 'object' && field.value && (field.value as ESignSignatureValue).mode === 'typed' ? (field.value as ESignSignatureValue).value || '' : ''; setTypedSignature(saved || (field.type === 'initials' ? initialsFor(session?.recipient.name || '') : session?.recipient.name || '')); setSignatureImage(''); }
  async function adoptSignature() { if (!signatureField) return; const signature: ESignSignatureValue = signatureMode === 'typed' ? { mode: 'typed', value: typedSignature.trim() } : { mode: signatureMode, dataUrl: signatureImage }; if (!(signature.value || signature.dataUrl)) return toast.error('Add a signature before applying it.'); try { setWorking(true); await saveField(signatureField.id, signature); setSignatureField(null); } finally { setWorking(false); } }
  const missing = useMemo(() => detail?.fields.filter((field) => !isComplete(field)) || [], [detail]);
  function nextRequired() { const field = missing[0]; if (!field) return; const element = document.querySelector<HTMLElement>(`[data-sign-field-id="${CSS.escape(field.id)}"]`); element?.scrollIntoView({ behavior: 'smooth', block: 'center' }); window.setTimeout(() => element?.focus(), 350); }
  async function finish() { if (pendingSavesRef.current > 0) return toast.message('Wait for your latest field changes to save.'); if (missing.length) { nextRequired(); return toast.error(`${missing.length} required field${missing.length === 1 ? ' is' : 's are'} incomplete.`); } try { setWorking(true); const next = await api<ESignPublicSession>('/api/public/esign/complete', json('POST', {})); setSession(next); await loadDetail(); setCompleted(true); window.scrollTo({ top: 0, behavior: 'smooth' }); } catch (reason) { toast.error(reason instanceof Error ? reason.message : 'The agreement could not be completed.'); } finally { setWorking(false); } }
  async function decline() { if (declineReason.trim().length < 2) return; try { setWorking(true); await api('/api/public/esign/decline', json('POST', { reason: declineReason.trim() })); setDeclineOpen(false); setSession((current) => current ? { ...current, recipient: { ...current.recipient, status: 'declined' } } : current); } catch (reason) { toast.error(reason instanceof Error ? reason.message : 'The agreement could not be declined.'); } finally { setWorking(false); } }

  if (loading) return <PublicFrame><div className="mx-auto mt-20 h-64 max-w-lg animate-pulse border bg-muted" /></PublicFrame>;
  if (error || !session) return <PublicFrame><main className="mx-auto max-w-lg px-4 py-16"><div className="border bg-card p-6"><AlertCircle className="h-6 w-6 text-destructive" /><h1 className="mt-4 text-xl font-semibold">Signing link unavailable</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{error || 'This invitation is invalid, expired, declined or has been voided.'}</p></div></main></PublicFrame>;
  if (session.recipient.status === 'declined') return <PublicFrame><main className="mx-auto max-w-lg px-4 py-16"><div className="border bg-card p-6"><h1 className="text-xl font-semibold">Agreement declined</h1><p className="mt-2 text-sm text-muted-foreground">Your response has been recorded and the sender has been notified.</p></div></main></PublicFrame>;
  if (!session.authenticated) return <PublicFrame><main className="mx-auto max-w-md px-4 py-16"><div className="border bg-card p-6"><LockKeyhole className="h-6 w-6 text-primary" /><h1 className="mt-4 text-xl font-semibold">Enter your access code</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{session.envelope.title} is protected. Ask the sender for the code they shared separately from this email.</p><form className="mt-6 space-y-4" onSubmit={authenticate}><div><Label className="field-label" htmlFor="signing-access-code">Access code</Label><Input id="signing-access-code" type="password" autoComplete="one-time-code" value={accessCode} onChange={(event) => setAccessCode(event.target.value)} required autoFocus /></div><Button className="w-full" disabled={working || !accessCode}>{working ? <Loader2 className="animate-spin" /> : <LockKeyhole />}{working ? 'Checking' : 'Continue'}</Button></form></div></main></PublicFrame>;
  if (!session.consented && session.envelope.status !== 'completed') return <PublicFrame><main className="mx-auto max-w-2xl px-4 py-12"><div className="border bg-card p-6 sm:p-8"><ShieldCheck className="h-6 w-6 text-primary" /><h1 className="mt-4 text-xl font-semibold">Review and consent</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Before opening “{session.envelope.title}”, review the electronic-record disclosure below.</p><div className="mt-6 border bg-muted/20 p-4 text-sm leading-6"><p>{session.disclosure.text}</p><p className="mt-3 text-xs text-muted-foreground">Disclosure version {session.disclosure.version}</p></div><label className="mt-5 flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 rounded border-input text-primary focus:ring-primary" checked={consentChecked} onChange={(event) => setConsentChecked(event.target.checked)} /><span><span className="font-medium">I agree to use electronic records and signatures for this agreement.</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">Do not continue if you are not the named recipient.</span></span></label><Button className="mt-6" disabled={!consentChecked || working} onClick={() => void consent()}>{working ? <Loader2 className="animate-spin" /> : <ChevronRight />}{working ? 'Opening' : 'Agree and review'}</Button></div></main></PublicFrame>;
  if (!detail) return <PublicFrame><div className="mx-auto mt-20 h-64 max-w-lg animate-pulse border bg-muted" /></PublicFrame>;
  if (completed) { const observer = ['cc', 'viewer'].includes(detail.recipient.role); return <PublicFrame><main className="mx-auto max-w-2xl px-4 py-12"><div className="border bg-card p-6 sm:p-8"><CheckCircle2 className="h-7 w-7 text-emerald-700" /><h1 className="mt-4 text-xl font-semibold">{observer ? 'Agreement complete' : 'Signing complete'}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{observer ? `“${detail.envelope.title}” has been completed and shared with you.` : `Your part of “${detail.envelope.title}” is complete. You can safely close this page.`}</p>{detail.artifacts.length > 0 && <div className="mt-6 space-y-2 border-t pt-5"><div className="text-sm font-semibold">Completed files</div>{detail.artifacts.map((artifact) => <Button variant="outline" className="w-full justify-start" asChild key={artifact.id}><a href={`/api/public/esign/artifacts/${artifact.id}/content`}><Download />{artifact.name}</a></Button>)}</div>}</div></main></PublicFrame>; }
  return <PublicFrame><div className="sticky top-0 z-30 flex min-h-14 flex-wrap items-center justify-between gap-3 border-b bg-background/95 px-4 py-2 backdrop-blur"><div className="min-w-0"><div className="truncate text-sm font-semibold">{detail.envelope.title}</div><div className="text-xs text-muted-foreground">Signing as {detail.recipient.name}</div></div><div className="flex items-center gap-2"><span className="text-xs text-muted-foreground">{pendingSaves ? 'Saving fields…' : `${missing.length} required remaining`}</span>{missing.length > 0 && <Button variant="outline" size="sm" onClick={nextRequired}>Next required <ChevronRight /></Button>}<Button size="sm" disabled={working || pendingSaves > 0 || missing.length > 0} onClick={() => void finish()}>{working ? <Loader2 className="animate-spin" /> : <FileSignature />}{working ? 'Finishing' : 'Finish'}</Button></div></div>
    <main className="bg-muted/35 px-3 py-6 sm:px-6"><div className="mx-auto max-w-[900px] space-y-10">{detail.documents.map((document) => <SigningDocument key={document.id} document={document} fields={detail.fields.filter((field) => field.documentId === document.id)} onLocalChange={localField} onSave={(fieldId, value) => void saveField(fieldId, value)} onAdoptSignature={openSignature} />)}<div className="flex flex-col justify-between gap-3 border bg-card p-4 sm:flex-row sm:items-center"><div><div className="text-sm font-semibold">Finished reviewing?</div><p className="mt-1 text-xs text-muted-foreground">Complete every required field, then select Finish.</p></div><div className="flex gap-2"><Button variant="ghost" onClick={() => setDeclineOpen(true)}>Decline</Button><Button disabled={working || pendingSaves > 0 || missing.length > 0} onClick={() => void finish()}><FileSignature />Finish</Button></div></div></div></main>
    <Dialog open={Boolean(signatureField)} onOpenChange={(open) => { if (!open) setSignatureField(null); }}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>{signatureField?.type === 'initials' ? 'Add initials' : 'Adopt your signature'}</DialogTitle><DialogDescription>Choose how your signature should appear on this agreement.</DialogDescription></DialogHeader><Tabs value={signatureMode} onValueChange={(value) => setSignatureMode(value as typeof signatureMode)}><TabsList className="w-full"><TabsTrigger value="typed">Type</TabsTrigger><TabsTrigger value="drawn">Draw</TabsTrigger><TabsTrigger value="uploaded">Upload</TabsTrigger></TabsList><TabsContent value="typed"><Label className="field-label" htmlFor="typed-signature">{signatureField?.type === 'initials' ? 'Initials' : 'Full name'}</Label><Input id="typed-signature" className="h-14 text-xl italic" value={typedSignature} maxLength={signatureField?.type === 'initials' ? 12 : 100} onChange={(event) => setTypedSignature(signatureField?.type === 'initials' ? event.target.value.toUpperCase() : event.target.value)} /></TabsContent><TabsContent value="drawn"><SignatureCanvas onChange={setSignatureImage} /></TabsContent><TabsContent value="uploaded"><label className="flex min-h-32 cursor-pointer flex-col items-center justify-center border border-dashed text-center"><FileSignature className="h-5 w-5 text-muted-foreground" /><span className="mt-2 text-sm font-medium">Choose a PNG or JPEG</span>{signatureImage && <span className="mt-1 text-xs text-emerald-700">Image ready</span>}<input className="sr-only" type="file" accept="image/png,image/jpeg" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; if (!['image/png', 'image/jpeg'].includes(file.type)) return toast.error('Choose a PNG or JPEG image.'); const reader = new FileReader(); reader.onload = () => setSignatureImage(String(reader.result || '')); reader.readAsDataURL(file); }} /></label></TabsContent></Tabs><DialogFooter><Button variant="outline" onClick={() => setSignatureField(null)}>Cancel</Button><Button disabled={working || (signatureMode === 'typed' ? !typedSignature.trim() : !signatureImage)} onClick={() => void adoptSignature()}>{working ? <Loader2 className="animate-spin" /> : <PenLine />}Apply</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={declineOpen} onOpenChange={setDeclineOpen}><DialogContent><DialogHeader><DialogTitle>Decline agreement</DialogTitle><DialogDescription>The sender will be notified and this signing process will stop.</DialogDescription></DialogHeader><div><Label className="field-label" htmlFor="decline-reason">Reason <span className="text-destructive">*</span></Label><Textarea id="decline-reason" value={declineReason} onChange={(event) => setDeclineReason(event.target.value)} rows={4} /></div><DialogFooter><Button variant="outline" onClick={() => setDeclineOpen(false)}>Cancel</Button><Button variant="destructive" disabled={working || declineReason.trim().length < 2} onClick={() => void decline()}>Decline agreement</Button></DialogFooter></DialogContent></Dialog>
  </PublicFrame>;
}
