// Assembles the workflow output (model specs) into:
//   - _schema_additions.prisma  (concatenated Prisma model blocks)
//   - generated.js              (array of { prismaKey, collectionName, transform })
// Validates each transform arrow parses, and flags dup keys.
//   node scripts/etl/_assemble.js <workflow-output-file>
const fs = require('fs');
const path = require('path');

const RAW = process.argv[2];
const parsed = JSON.parse(fs.readFileSync(RAW, 'utf8'));
const models = (parsed.result && parsed.result.models) || parsed.models;
if (!Array.isArray(models)) { console.error('no models[] in output'); process.exit(1); }

const seen = new Set();
const issues = [];
const blocks = [];
const entries = [];

for (const m of models) {
  if (seen.has(m.prismaKey)) { issues.push(`dup prismaKey: ${m.prismaKey}`); continue; }
  seen.add(m.prismaKey);
  try {
    const fn = eval('(' + m.transformArrow + ')');
    if (typeof fn !== 'function') issues.push(`not a function: ${m.modelName}`);
  } catch (e) {
    issues.push(`arrow syntax (${m.modelName}): ${e.message}`);
  }
  blocks.push(`// ---- ${m.modelName} (lossless structural copy) ----\n${m.prismaBlock}`);
  entries.push(`  { prismaKey: ${JSON.stringify(m.prismaKey)}, collectionName: ${JSON.stringify(m.collectionName)}, transform: ${m.transformArrow} },`);
}

fs.writeFileSync(path.join(__dirname, '_schema_additions.prisma'), blocks.join('\n\n') + '\n');
fs.writeFileSync(
  path.join(__dirname, 'generated.js'),
  `// AUTO-GENERATED by scripts/etl/_assemble.js — lossless structural-copy transforms.\nconst { oid, asDate } = require('./lib');\nmodule.exports = [\n${entries.join('\n')}\n];\n`
);

console.log(`models=${models.length} blocks=${blocks.length}`);
console.log('prismaKey / collection:');
for (const m of models) console.log(`  ${m.prismaKey.padEnd(24)} ${m.collectionName}`);
console.log(issues.length ? 'ISSUES:\n - ' + issues.join('\n - ') : '✅ no assembly issues');
