export type QuestionType = 'single_choice' | 'multiple_choice' | 'nps' | 'csat' | 'ces' | 'short_text' | 'long_text' | 'email' | 'number' | 'rating' | 'slider' | 'ranking' | 'matrix' | 'date' | 'contact' | 'file' | 'media' | 'statement';
export interface LogicRule { action: 'show' | 'hide' | 'skip_to' | 'create_ticket'; sourceQuestionId: string; operator: string; value: string | number; targetQuestionId?: string }
export interface Question { id: string; surveyId: string; page: number; position: number; type: QuestionType; title: string; description: string; required: boolean; options: string[]; settings: Record<string, any>; logic: LogicRule[] }
export interface Survey { id: string; title: string; description: string; purpose: 'customer_experience' | 'employee_experience' | 'market_research'; audience: string; status: 'draft' | 'live' | 'closed'; primaryMetric: 'nps' | 'csat' | 'ces' | 'custom'; language: string; thankYouMessage: string; theme: Record<string, any>; settings: Record<string, any>; createdAt: string; updatedAt: string; publishedAt: string | null; questions?: Question[]; responseCount?: number; collectorCount?: number }
export interface Collector { id: string; surveyId: string; name: string; type: 'web' | 'email' | 'api' | 'qr' | 'manual' | 'kiosk'; slug: string; status: 'open' | 'closed'; settings: Record<string, any>; createdAt: string; publicUrl: string; responseCount?: number; recipientCount?: number }
export interface ResponseRecord { id: string; surveyId: string; collectorId: string; respondentToken: string; status: 'partial' | 'completed'; answers: Record<string, any>; metadata: Record<string, any>; startedAt: string; completedAt: string | null; durationSeconds: number | null; aiAnalysis: any; analyzedAt: string | null }
export interface AiJob { id: string; kind: string; surveyId: string | null; responseId: string | null; state: 'queued' | 'processing' | 'completed' | 'failed'; stage: string; progress: number; attempt: number; input: Record<string, any>; result: any; error: string | null; retryAt: string | null; createdAt: string; startedAt: string | null; completedAt: string | null; updatedAt: string }
export interface Template { id: string; name: string; description: string; purpose: Survey['purpose']; primaryMetric: Survey['primaryMetric']; audience: string; questions: Partial<Question>[] }
export interface SurveyDetail { survey: Survey; collectors: Collector[]; insights: { id: string; kind: string; payload: any; createdAt: string }[] }
