import crypto from 'node:crypto';
import { db } from './database.js';
import { assertSubscriptionFeature } from './subscriptionEntitlements.js';
import { effectiveJourneyRole } from './journeyCollaboration.js';
import { createJourneyPredictionAudit, evaluateJourneyPrediction, validateJourneyPredictiveModel,
  type JourneyPredictionPolicy, type JourneyPredictionRequest, type JourneyPredictionTarget,
  type JourneyPredictiveModel } from './journeyPredictiveGovernance.js';

export class JourneyPredictiveRepositoryError extends Error { constructor(message:string,public status=400,
  public code='JOURNEY_PREDICTIVE_INVALID',public details:Record<string,unknown>={}){super(message);this.name='JourneyPredictiveRepositoryError';}}
const now=()=>new Date().toISOString(); const hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');
const json=(v:unknown)=>JSON.stringify(v); const parse=<T>(v:unknown)=>JSON.parse(String(v)) as T;
function ensure(){if(db.provider!=='sqlite')return;db.exec(`
CREATE TABLE IF NOT EXISTS journey_prediction_policies(space_id TEXT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,target TEXT NOT NULL,
 enabled INTEGER NOT NULL,purpose TEXT NOT NULL,policy_json TEXT NOT NULL CHECK(json_valid(policy_json)),revision INTEGER NOT NULL,
 updated_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(space_id,target));
CREATE TABLE IF NOT EXISTS journey_predictive_models(id TEXT PRIMARY KEY,space_id TEXT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
 target TEXT NOT NULL,name TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN('approved','retired')),revision INTEGER NOT NULL,
 current_version_id TEXT NOT NULL,created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,
 UNIQUE(id,space_id),UNIQUE(current_version_id,id,space_id));
CREATE TABLE IF NOT EXISTS journey_predictive_model_versions(id TEXT PRIMARY KEY,model_id TEXT NOT NULL,space_id TEXT NOT NULL,
 version TEXT NOT NULL,model_json TEXT NOT NULL CHECK(json_valid(model_json)),content_sha256 TEXT NOT NULL,approved_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
 approved_at TEXT NOT NULL,UNIQUE(id,model_id,space_id),UNIQUE(model_id,space_id,version),FOREIGN KEY(model_id,space_id) REFERENCES journey_predictive_models(id,space_id));
CREATE TABLE IF NOT EXISTS journey_prediction_drift_evaluations(id TEXT PRIMARY KEY,model_version_id TEXT NOT NULL,model_id TEXT NOT NULL,space_id TEXT NOT NULL,
 population_stability_index REAL,missing_feature_ratio REAL,out_of_distribution_score REAL,decision TEXT NOT NULL,reason_codes_json TEXT NOT NULL CHECK(json_valid(reason_codes_json)),
 evaluated_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,evaluated_at TEXT NOT NULL,FOREIGN KEY(model_version_id,model_id,space_id) REFERENCES journey_predictive_model_versions(id,model_id,space_id));
CREATE TABLE IF NOT EXISTS journey_prediction_runs(id TEXT PRIMARY KEY,space_id TEXT NOT NULL REFERENCES spaces(id) ON DELETE NO ACTION,
 model_id TEXT NOT NULL,model_version_id TEXT NOT NULL,evaluator_kind TEXT NOT NULL CHECK(evaluator_kind='governed_fixture'),evaluator_output_sha256 TEXT NOT NULL,
 result_json TEXT NOT NULL CHECK(json_valid(result_json)),result_sha256 TEXT NOT NULL,actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL,
 FOREIGN KEY(model_version_id,model_id,space_id) REFERENCES journey_predictive_model_versions(id,model_id,space_id));
CREATE INDEX IF NOT EXISTS journey_prediction_runs_list ON journey_prediction_runs(space_id,created_at DESC,id);
CREATE TABLE IF NOT EXISTS journey_prediction_audit(id TEXT PRIMARY KEY,space_id TEXT NOT NULL REFERENCES spaces(id) ON DELETE NO ACTION,
 actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,action TEXT NOT NULL,target_type TEXT NOT NULL,target_id TEXT NOT NULL,
 detail_json TEXT NOT NULL CHECK(json_valid(detail_json)),detail_sha256 TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS journey_predictive_versions_append_only BEFORE UPDATE ON journey_predictive_model_versions BEGIN SELECT RAISE(ABORT,'append-only');END;
CREATE TRIGGER IF NOT EXISTS journey_predictive_versions_delete_guard BEFORE DELETE ON journey_predictive_model_versions BEGIN SELECT RAISE(ABORT,'append-only');END;
CREATE TRIGGER IF NOT EXISTS journey_prediction_drift_append_only BEFORE UPDATE ON journey_prediction_drift_evaluations BEGIN SELECT RAISE(ABORT,'append-only');END;
CREATE TRIGGER IF NOT EXISTS journey_prediction_drift_delete_guard BEFORE DELETE ON journey_prediction_drift_evaluations BEGIN SELECT RAISE(ABORT,'append-only');END;
CREATE TRIGGER IF NOT EXISTS journey_prediction_runs_append_only BEFORE UPDATE ON journey_prediction_runs BEGIN SELECT RAISE(ABORT,'append-only');END;
CREATE TRIGGER IF NOT EXISTS journey_prediction_runs_delete_guard BEFORE DELETE ON journey_prediction_runs BEGIN SELECT RAISE(ABORT,'append-only');END;
CREATE TRIGGER IF NOT EXISTS journey_prediction_audit_append_only BEFORE UPDATE ON journey_prediction_audit BEGIN SELECT RAISE(ABORT,'append-only');END;
CREATE TRIGGER IF NOT EXISTS journey_prediction_audit_delete_guard BEFORE DELETE ON journey_prediction_audit BEGIN SELECT RAISE(ABORT,'append-only');END;`)}ensure();
function access(spaceId:string,userId:string,capability:'journeys.read'|'journeys.review'){
 assertSubscriptionFeature(spaceId,'journeyActualPaths');
 const row=db.prepare('SELECT 1 FROM space_memberships WHERE space_id=? AND user_id=?').get(spaceId,userId);
 if(!row)throw new JourneyPredictiveRepositoryError('Space membership is required.',403,'JOURNEY_PREDICTIVE_MEMBERSHIP_REQUIRED');
 if(!effectiveJourneyRole(spaceId,userId).capabilities.has(capability))throw new JourneyPredictiveRepositoryError(
  `Journey ${capability==='journeys.read'?'read':'review'} capability is required.`,403,
  capability==='journeys.read'?'JOURNEY_PREDICTIVE_READ_REQUIRED':'JOURNEY_PREDICTIVE_REVIEW_REQUIRED')}
function role(spaceId:string,userId:string){access(spaceId,userId,'journeys.read')}
function manage(spaceId:string,userId:string){access(spaceId,userId,'journeys.review')}
function safeAudit(spaceId:string,actor:string,action:string,type:string,id:string,detail:Record<string,unknown>,at:string){const data=json(detail);
 if(/subjectId|featureValues|featureContributions/iu.test(data))throw new JourneyPredictiveRepositoryError('Predictive audit content is unsafe.',500,'JOURNEY_PREDICTIVE_AUDIT_UNSAFE');
 db.prepare('INSERT INTO journey_prediction_audit(id,space_id,actor_user_id,action,target_type,target_id,detail_json,detail_sha256,created_at) VALUES(?,?,?,?,?,?,?,?,?)')
 .run(crypto.randomUUID(),spaceId,actor,action,type,id,data,hash(data),at)}
const defaultPolicy=(target:JourneyPredictionTarget):JourneyPredictionPolicy=>({enabled:false,purpose:`journey_${target}_decision_support`,minimumTrainingSamples:1000,
 minimumClassSamples:100,minimumValidationSamples:200,minimumAreaUnderRoc:.7,maximumBrierScore:.25,maximumPopulationStabilityIndex:.2,maximumMissingFeatureRatio:.1,maximumOutOfDistributionScore:10});
function policyRow(row:any,target:JourneyPredictionTarget){if(!row)return{target,policy:defaultPolicy(target),revision:0,updatedAt:null};return{target,policy:parse<JourneyPredictionPolicy>(row.policy_json),revision:Number(row.revision),updatedAt:String(row.updated_at)}}
function modelRow(row:any){return{id:String(row.id),target:row.target,name:String(row.name),state:row.state,revision:Number(row.revision),currentVersionId:String(row.current_version_id),createdAt:String(row.created_at),updatedAt:String(row.updated_at)}}
function getModel(spaceId:string,id:string){const row=db.prepare('SELECT * FROM journey_predictive_models WHERE id=? AND space_id=?').get(id,spaceId)as any;if(!row)throw new JourneyPredictiveRepositoryError('Predictive model not found.',404,'JOURNEY_PREDICTIVE_MODEL_NOT_FOUND');return row}
function getVersion(spaceId:string,id:string){const row=db.prepare('SELECT * FROM journey_predictive_model_versions WHERE id=? AND space_id=?').get(id,spaceId)as any;if(!row)throw new JourneyPredictiveRepositoryError('Predictive model version not found.',404,'JOURNEY_PREDICTIVE_VERSION_NOT_FOUND');return row}
export function listPredictiveGovernance(input:{spaceId:string;actorUserId:string}){role(input.spaceId,input.actorUserId);const models=(db.prepare('SELECT * FROM journey_predictive_models WHERE space_id=? ORDER BY updated_at DESC,id').all(input.spaceId)as any[]).map(modelRow);
 const policies=(['churn','conversion']as JourneyPredictionTarget[]).map(target=>policyRow(db.prepare('SELECT * FROM journey_prediction_policies WHERE space_id=? AND target=?').get(input.spaceId,target),target));return{models,policies}}
export function readPredictiveModel(input:{spaceId:string;actorUserId:string;modelId:string}){role(input.spaceId,input.actorUserId);const m=getModel(input.spaceId,input.modelId);const versions=(db.prepare('SELECT * FROM journey_predictive_model_versions WHERE model_id=? AND space_id=? ORDER BY approved_at DESC').all(input.modelId,input.spaceId)as any[]).map(r=>{const{spaceId:_spaceId,...model}=parse<JourneyPredictiveModel>(r.model_json);return{id:String(r.id),model,contentSha256:String(r.content_sha256),approvedAt:String(r.approved_at)}});return{model:modelRow(m),versions}}
export function updatePredictionPolicy(input:{spaceId:string;actorUserId:string;target:JourneyPredictionTarget;expectedRevision:number;policy:JourneyPredictionPolicy}){manage(input.spaceId,input.actorUserId);const at=now();const existing=db.prepare('SELECT revision FROM journey_prediction_policies WHERE space_id=? AND target=?').get(input.spaceId,input.target)as any;
 if(Number(existing?.revision||0)!==input.expectedRevision)throw new JourneyPredictiveRepositoryError('Policy revision conflict.',409,'JOURNEY_PREDICTIVE_POLICY_CONFLICT',{currentRevision:Number(existing?.revision||0)});const revision=input.expectedRevision+1;
 db.transaction(()=>{db.prepare(`INSERT INTO journey_prediction_policies(space_id,target,enabled,purpose,policy_json,revision,updated_by_user_id,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?,?)
 ON CONFLICT(space_id,target)DO UPDATE SET enabled=excluded.enabled,purpose=excluded.purpose,policy_json=excluded.policy_json,revision=excluded.revision,updated_by_user_id=excluded.updated_by_user_id,updated_at=excluded.updated_at`)
 .run(input.spaceId,input.target,input.policy.enabled?1:0,input.policy.purpose,json(input.policy),revision,input.actorUserId,at,at);safeAudit(input.spaceId,input.actorUserId,'policy.updated','policy',input.target,{target:input.target,revision,enabled:input.policy.enabled},at)})();return policyRow(db.prepare('SELECT * FROM journey_prediction_policies WHERE space_id=? AND target=?').get(input.spaceId,input.target),input.target)}
type ModelApprovalEvidence=Omit<JourneyPredictiveModel,'spaceId'|'approvedByUserId'|'approvedAt'|'state'|'contentSha256'>;
export function approvePredictiveModel(input:{spaceId:string;actorUserId:string;name:string;model:ModelApprovalEvidence}){manage(input.spaceId,input.actorUserId);
 const trainer=db.prepare('SELECT 1 FROM space_memberships WHERE space_id=? AND user_id=?').get(input.spaceId,input.model.trainedByUserId);
 if(!trainer)throw new JourneyPredictiveRepositoryError('The model trainer must be a current space member.',422,'JOURNEY_PREDICTIVE_TRAINER_INVALID');
 const unsigned={...input.model,spaceId:input.spaceId,approvedByUserId:input.actorUserId,approvedAt:now(),state:'approved' as const};
 const governed:JourneyPredictiveModel={...unsigned,contentSha256:hash(json(unsigned))};const issues=validateJourneyPredictiveModel(governed);if(issues.length)throw new JourneyPredictiveRepositoryError('Model approval evidence is invalid.',422,'JOURNEY_PREDICTIVE_MODEL_INVALID',{issues});
 const at=governed.approvedAt,id=governed.id,versionId=crypto.randomUUID();
 db.transaction(()=>{db.prepare(`INSERT INTO journey_predictive_models(id,space_id,target,name,state,revision,current_version_id,created_by_user_id,created_at,updated_at)VALUES(?,?,?,?, 'approved',1,?,?,?,?)`).run(id,input.spaceId,governed.target,input.name,versionId,input.actorUserId,at,at);
 db.prepare('INSERT INTO journey_predictive_model_versions(id,model_id,space_id,version,model_json,content_sha256,approved_by_user_id,approved_at)VALUES(?,?,?,?,?,?,?,?)').run(versionId,id,input.spaceId,governed.version,json(governed),governed.contentSha256,input.actorUserId,at);
 safeAudit(input.spaceId,input.actorUserId,'model.approved','model',id,{target:governed.target,version:governed.version,contentSha256:governed.contentSha256},at)})();return readPredictiveModel({...input,modelId:id})}
export function retirePredictiveModel(input:{spaceId:string;actorUserId:string;modelId:string;expectedRevision:number}){manage(input.spaceId,input.actorUserId);getModel(input.spaceId,input.modelId);const at=now();const changed=db.prepare("UPDATE journey_predictive_models SET state='retired',revision=revision+1,updated_at=? WHERE id=? AND space_id=? AND revision=?").run(at,input.modelId,input.spaceId,input.expectedRevision);if(!changed.changes)throw new JourneyPredictiveRepositoryError('Model revision conflict.',409,'JOURNEY_PREDICTIVE_MODEL_CONFLICT');safeAudit(input.spaceId,input.actorUserId,'model.retired','model',input.modelId,{revision:input.expectedRevision+1},at);return modelRow(getModel(input.spaceId,input.modelId))}
export function recordDriftEvaluation(input:{spaceId:string;actorUserId:string;modelId:string;modelVersionId:string;populationStabilityIndex:number|null;missingFeatureRatio:number;outOfDistributionScore:number|null}){manage(input.spaceId,input.actorUserId);const v=getVersion(input.spaceId,input.modelVersionId);const model=parse<JourneyPredictiveModel>(v.model_json);if(model.id!==input.modelId)throw new JourneyPredictiveRepositoryError('Predictive model version not found.',404,'JOURNEY_PREDICTIVE_VERSION_NOT_FOUND');const p=policyRow(db.prepare('SELECT * FROM journey_prediction_policies WHERE space_id=? AND target=?').get(input.spaceId,model.target),model.target).policy;
 const reasons:string[]=[];if(input.populationStabilityIndex===null)reasons.push('DRIFT_EVIDENCE_MISSING');else if(input.populationStabilityIndex>p.maximumPopulationStabilityIndex)reasons.push('POPULATION_DRIFT_EXCEEDED');if(input.missingFeatureRatio>p.maximumMissingFeatureRatio)reasons.push('FEATURE_COVERAGE_INSUFFICIENT');if(input.outOfDistributionScore===null)reasons.push('DISTRIBUTION_EVIDENCE_MISSING');else if(input.outOfDistributionScore>p.maximumOutOfDistributionScore)reasons.push('OUT_OF_DISTRIBUTION');const id=crypto.randomUUID(),at=now(),decision=reasons.length?'abstain':'within_envelope';db.prepare('INSERT INTO journey_prediction_drift_evaluations(id,model_version_id,model_id,space_id,population_stability_index,missing_feature_ratio,out_of_distribution_score,decision,reason_codes_json,evaluated_by_user_id,evaluated_at)VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,input.modelVersionId,model.id,input.spaceId,input.populationStabilityIndex,input.missingFeatureRatio,input.outOfDistributionScore,decision,json(reasons),input.actorUserId,at);safeAudit(input.spaceId,input.actorUserId,'drift.evaluated','model',model.id,{decision,reasonCodes:reasons,modelVersion:model.version},at);return{id,modelId:model.id,modelVersionId:input.modelVersionId,decision,reasonCodes:reasons,evaluatedAt:at}}
type GovernedFixtureRequest=Omit<JourneyPredictionRequest,'spaceId'|'populationStabilityIndex'|'outOfDistributionScore'>;
export function evaluatePersistedPrediction(input:{spaceId:string;actorUserId:string;modelVersionId:string;evaluatorKind:'governed_fixture';request:GovernedFixtureRequest}){manage(input.spaceId,input.actorUserId);const v=getVersion(input.spaceId,input.modelVersionId);const model=parse<JourneyPredictiveModel>(v.model_json);const parent=getModel(input.spaceId,model.id);if(parent.state!=='approved')throw new JourneyPredictiveRepositoryError('Retired models cannot accept evaluation fixtures.',422,'JOURNEY_PREDICTIVE_MODEL_RETIRED');const policy=policyRow(db.prepare('SELECT * FROM journey_prediction_policies WHERE space_id=? AND target=?').get(input.spaceId,model.target),model.target).policy;
 const drift=db.prepare('SELECT * FROM journey_prediction_drift_evaluations WHERE space_id=? AND model_version_id=? ORDER BY evaluated_at DESC,id DESC LIMIT 1').get(input.spaceId,input.modelVersionId)as any;const stale=Boolean(drift&&Date.parse(input.request.sourceWindow.to)-Date.parse(String(drift.evaluated_at))>30*24*60*60*1000);let result;try{result=evaluateJourneyPrediction({model,policy,request:{...input.request,spaceId:input.spaceId,populationStabilityIndex:!drift||stale?null:drift.population_stability_index===null?null:Number(drift.population_stability_index),outOfDistributionScore:!drift||stale?null:drift.out_of_distribution_score===null?null:Number(drift.out_of_distribution_score)}})}catch(e){throw new JourneyPredictiveRepositoryError(e instanceof Error?e.message:'Evaluation invalid.',422,'JOURNEY_PREDICTIVE_EVALUATION_INVALID')};if(stale){result=Object.freeze({...result,decision:'abstained' as const,score:null,confidence:null,reasonCodes:Object.freeze([...new Set([...result.reasonCodes,'DRIFT_EVIDENCE_STALE'])].sort()),explanation:Object.freeze([]),limitations:Object.freeze([...result.limitations,'The latest persisted drift evaluation is stale.'])})}const id=crypto.randomUUID(),at=now(),serialized=json(result),evaluatorOutputSha256=hash(json(input.request));db.transaction(()=>{db.prepare('INSERT INTO journey_prediction_runs(id,space_id,model_id,model_version_id,evaluator_kind,evaluator_output_sha256,result_json,result_sha256,actor_user_id,created_at)VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,input.spaceId,model.id,input.modelVersionId,input.evaluatorKind,evaluatorOutputSha256,serialized,hash(serialized),input.actorUserId,at);const a=createJourneyPredictionAudit({spaceId:input.spaceId,actorUserId:input.actorUserId,result,createdAt:at});safeAudit(input.spaceId,input.actorUserId,a.action,'run',id,a.detail,at)})();return{id,result,evaluatorKind:input.evaluatorKind,evaluatorOutputSha256,createdAt:at}}
export function listPredictionRuns(input:{spaceId:string;actorUserId:string;limit?:number}){role(input.spaceId,input.actorUserId);return(db.prepare('SELECT id,model_id,model_version_id,evaluator_kind,evaluator_output_sha256,result_json,result_sha256,created_at FROM journey_prediction_runs WHERE space_id=? ORDER BY created_at DESC,id LIMIT ?').all(input.spaceId,Math.min(100,input.limit||50))as any[]).map(r=>({id:String(r.id),modelId:String(r.model_id),modelVersionId:String(r.model_version_id),evaluatorKind:r.evaluator_kind,evaluatorOutputSha256:String(r.evaluator_output_sha256),result:parse(r.result_json),resultSha256:String(r.result_sha256),createdAt:String(r.created_at)}))}
