const crypto = require('crypto');
const { AttendanceException } = require('../models');

const EXPLANATIONS = {
    late_arrival: 'The first clock-in was later than the scheduled start plus the configured grace period.',
    early_departure: 'The final clock-out was earlier than the scheduled end minus the configured grace period.',
    absence: 'A scheduled work day had no attendance event, approved leave or public holiday.',
    missed_break: 'The recorded work duration met the break threshold but no completed break was found.',
    long_break: 'Completed breaks exceeded the configured break duration.',
    no_clock_out: 'A clock-in did not have a later clock-out in the attendance session.',
    overtime: 'Calculated time exceeded an effective daily or weekly overtime threshold.',
    insufficient_rest: 'The time between one completed work session and the next was below the configured minimum rest.',
    geofence_failure: 'A location-bearing attendance event was not verified against a permitted geofence.',
    duplicate_session: 'Overlapping or repeated clock events created an unusual session pattern.',
    leave_conflict: 'Recorded attendance overlaps leave that Leave Management reports as approved.',
};

function fingerprint(timesheet, day, exception) {
    return crypto.createHash('sha256').update([
        timesheet.organizationId, timesheet.userId, timesheet._id, timesheet.version || 1,
        new Date(day.date).toISOString().slice(0, 10), exception.type, exception.description,
    ].join('|')).digest('hex');
}

async function syncTimesheetExceptions(timesheet) {
    const active = [];
    for (const day of timesheet.dailyEntries || []) {
        for (const exception of day.exceptions || []) {
            const id = fingerprint(timesheet, day, exception);
            active.push(id);
            await AttendanceException.findOneAndUpdate(
                { fingerprint: id },
                { $setOnInsert: {
                    organizationId: timesheet.organizationId,
                    userId: timesheet.userId,
                    userEmail: timesheet.userEmail,
                    userName: timesheet.userName,
                    timesheetId: timesheet._id,
                    timesheetVersion: timesheet.version || 1,
                    occurrenceDate: day.date,
                    type: exception.type,
                    ruleKey: `attendance.${exception.type}`,
                    description: exception.description,
                    minutes: exception.minutes,
                    explanation: EXPLANATIONS[exception.type] || 'This exception was generated by an explicit attendance validation rule.',
                    calculation: { exception, dayStatus: day.status, clockIn: day.clockIn, clockOut: day.clockOut },
                    rulePack: { id: timesheet.policySnapshot?.rulePackId, version: timesheet.policySnapshot?.rulePackVersion },
                    auditLog: [{ action: 'detected', actorId: 'system', actorName: 'Attendance calculation', details: exception.description }],
                } },
                { upsert: true, new: true, setDefaultsOnInsert: true }
            );
        }
    }
    await AttendanceException.updateMany(
        { timesheetId: timesheet._id, timesheetVersion: timesheet.version || 1, fingerprint: { $nin: active }, status: 'open' },
        { $set: { status: 'resolved' }, $push: { auditLog: { action: 'no_longer_detected', actorId: 'system', actorName: 'Attendance calculation', details: 'The latest recalculation no longer detects this exception' } } }
    );
    return active.length;
}

module.exports = { EXPLANATIONS, syncTimesheetExceptions };
