'use client';

import { useEffect, useMemo, useState } from 'react';
import { AlertCircle as CircleAlert, CalendarClock, Check, Plus, Send, Users } from 'lucide-react';
import { schedulingApi } from '@/lib/api';
import { useAuth } from '@/context/AuthContext';

function localInput(date: Date) { return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

export default function SchedulePage() {
    const { user } = useAuth();
    const [shifts, setShifts] = useState<any[]>([]); const [openShifts, setOpenShifts] = useState<any[]>([]); const [requests, setRequests] = useState<any[]>([]); const [templates, setTemplates] = useState<any[]>([]);
    const [message, setMessage] = useState(''); const [showCreate, setShowCreate] = useState(false);
    const [form, setForm] = useState<any>({ userId: '', startAt: localInput(new Date(Date.now() + 86400000)), endAt: localInput(new Date(Date.now() + 86400000 + 8 * 3600000)), workMode: 'office', breakMinutes: 60, openShift: false });
    const role = user?.currentOrganization?.role; const manager = ['owner', 'admin', 'hr_manager'].includes(role) || user?.teams?.some(t => t.organizationId === user?.currentOrganization?.id && ['line_manager', 'team_lead'].includes(t.role));
    const range = useMemo(() => ({ start: new Date(Date.now() - 7 * 86400000).toISOString(), end: new Date(Date.now() + 35 * 86400000).toISOString() }), []);
    const load = async () => {
        const [mine, open, requestData, templateData] = await Promise.all([schedulingApi.getShifts(range), schedulingApi.getShifts({ ...range, open: true, status: 'published' }), schedulingApi.getRequests(), schedulingApi.getTemplates()]);
        setShifts(mine.shifts || []); setOpenShifts(open.shifts || []); setRequests(requestData.requests || []); setTemplates(templateData.templates || []);
    };
    useEffect(() => { void load().catch(() => setMessage('Schedule could not be loaded.')); }, []);
    const createShift = async () => { await schedulingApi.createShift({ ...form, userId: form.openShift ? null : form.userId || user?.id, startAt: new Date(form.startAt), endAt: new Date(form.endAt) }); setShowCreate(false); setMessage('Draft shift created.'); await load(); };
    const publish = async () => { const start = new Date(); start.setHours(0, 0, 0, 0); const end = new Date(start.getTime() + 35 * 86400000); const result = await schedulingApi.publish({ periodStart: start, periodEnd: end, note: 'Published from schedule workspace' }); setMessage(`${result.publishedCount} shift${result.publishedCount === 1 ? '' : 's'} published.`); await load(); };
    const acknowledge = async (id: string, accepted: boolean) => { await schedulingApi.acknowledge(id, accepted); await load(); };
    const requestCover = async (id: string) => { await schedulingApi.createRequest({ shiftId: id, type: 'cover', reason: 'I am available to cover this shift.' }); setMessage('Cover request sent for manager approval.'); await load(); };
    const review = async (id: string, approved: boolean) => { await schedulingApi.reviewRequest(id, approved); await load(); };

    return <div className="space-y-6">
        <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold text-white">Schedule</h1><p className="mt-1 text-sm text-zinc-400">Published shifts, availability, open cover and schedule acknowledgements.</p></div>{manager && <div className="flex gap-2"><button onClick={() => setShowCreate(!showCreate)} className="inline-flex items-center gap-2 rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm text-white"><Plus className="h-4 w-4" />New shift</button><button onClick={publish} className="inline-flex items-center gap-2 rounded-lg bg-teal-600 px-3 py-2 text-sm font-medium text-white hover:bg-teal-500"><Send className="h-4 w-4" />Publish drafts</button></div>}</div>
        {message && <div className="rounded-lg border border-teal-500/30 bg-teal-500/10 px-4 py-3 text-sm text-teal-200">{message}</div>}
        {showCreate && <section className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-5"><h2 className="text-sm font-semibold text-white">Create a draft shift</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><input placeholder="Employee ID (blank for yourself)" value={form.userId} onChange={e => setForm({ ...form, userId: e.target.value })} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm" /><input type="datetime-local" value={form.startAt} onChange={e => setForm({ ...form, startAt: e.target.value })} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm" /><input type="datetime-local" value={form.endAt} onChange={e => setForm({ ...form, endAt: e.target.value })} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm" /><select value={form.workMode} onChange={e => setForm({ ...form, workMode: e.target.value })} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"><option value="office">Office</option><option value="remote">Remote</option><option value="client_site">Client site</option><option value="other">Other</option></select><select value={form.templateId || ''} onChange={e => setForm({ ...form, templateId: e.target.value || undefined })} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"><option value="">No template</option>{templates.map(t => <option key={t._id} value={t._id}>{t.name}</option>)}</select><label className="flex items-center gap-2 px-2 text-sm text-zinc-300"><input type="checkbox" checked={form.openShift} onChange={e => setForm({ ...form, openShift: e.target.checked })} />Publish as open cover</label></div><button onClick={createShift} className="mt-4 rounded-lg bg-teal-600 px-4 py-2 text-sm font-medium text-white">Create draft</button></section>}
        <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]"><section className="overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900/50"><div className="flex items-center justify-between border-b border-zinc-800 px-5 py-4"><h2 className="flex items-center gap-2 text-sm font-semibold text-white"><CalendarClock className="h-4 w-4 text-teal-400" />Upcoming shifts</h2><span className="text-xs text-zinc-500">{shifts.length} scheduled</span></div>{shifts.length ? shifts.map(shift => <div key={shift._id} className="border-b border-zinc-800 px-5 py-4 last:border-0"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-sm font-medium text-zinc-100">{new Date(shift.startAt).toLocaleDateString(undefined, { weekday: 'short', day: 'numeric', month: 'short' })}</div><div className="mt-1 text-sm text-zinc-400">{new Date(shift.startAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} – {new Date(shift.endAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · {shift.workMode.replace('_', ' ')}</div><div className="mt-1 text-xs text-zinc-600">{shift.userId === user?.id ? 'You' : `Employee ${shift.userId || 'open'}`} · {shift.status}</div></div>{shift.userId === user?.id && shift.status === 'published' && shift.acknowledgement?.status === 'pending' && <div className="flex gap-2"><button onClick={() => acknowledge(shift._id, true)} className="rounded-md border border-teal-500/40 px-2.5 py-1.5 text-xs text-teal-300">Acknowledge</button><button onClick={() => acknowledge(shift._id, false)} className="rounded-md border border-zinc-700 px-2.5 py-1.5 text-xs text-zinc-400">Flag issue</button></div>}</div></div>) : <div className="p-10 text-center text-sm text-zinc-500">No shifts in the next five weeks.</div>}</section>
        <aside className="space-y-6"><section className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-5"><h2 className="flex items-center gap-2 text-sm font-semibold text-white"><Users className="h-4 w-4 text-zinc-500" />Open shifts</h2><div className="mt-4 space-y-4">{openShifts.length ? openShifts.map(shift => <div key={shift._id} className="border-b border-zinc-800 pb-4 last:border-0 last:pb-0"><div className="text-sm text-zinc-200">{new Date(shift.startAt).toLocaleString()}</div><button onClick={() => requestCover(shift._id)} className="mt-2 text-xs font-medium text-teal-400 hover:text-teal-300">Request cover</button></div>) : <p className="text-sm text-zinc-500">No open shifts.</p>}</div></section>
        <section className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-5"><h2 className="flex items-center gap-2 text-sm font-semibold text-white"><CircleAlert className="h-4 w-4 text-zinc-500" />Requests</h2><div className="mt-4 space-y-3">{requests.length ? requests.slice(0, 8).map(request => <div key={request._id} className="text-xs"><div className="flex justify-between"><span className="capitalize text-zinc-300">{request.type}</span><span className="text-zinc-500">{request.status}</span></div>{manager && request.status === 'pending' && <div className="mt-2 flex gap-3"><button onClick={() => review(request._id, true)} className="flex items-center gap-1 text-teal-400"><Check className="h-3 w-3" />Approve</button><button onClick={() => review(request._id, false)} className="text-zinc-400">Reject</button></div>}</div>) : <p className="text-sm text-zinc-500">No requests.</p>}</div></section></aside></div>
    </div>;
}
