'use client';

import { useEffect, useState } from 'react';
import { Beaker, CheckCircle2, Copy, ExternalLink, Save, Scale, Send } from 'lucide-react';
import { correctionRunsApi, rulePacksApi } from '@/lib/api';

export default function RulePackStudioPage() {
    const [packs, setPacks] = useState<any[]>([]); const [selected, setSelected] = useState<any>(null); const [resolved, setResolved] = useState<any>(null); const [compareId, setCompareId] = useState(''); const [comparison, setComparison] = useState<any>(null); const [rulesText, setRulesText] = useState('{}'); const [message, setMessage] = useState(''); const [validation, setValidation] = useState<any>(null); const [simulation, setSimulation] = useState<any>(null);
    const load = async () => { const data = await rulePacksApi.list(); setPacks(data.packs || []); if (!selected && data.packs?.length) await select(data.packs[0]._id); };
    const select = async (id: string) => { const data = await rulePacksApi.get(id); setSelected(data.pack); setResolved(data.resolved); setRulesText(JSON.stringify(data.pack.rules || {}, null, 2)); setValidation(null); setSimulation(null); };
    useEffect(() => { void load().catch(() => setMessage('Rule packs could not be loaded.')); }, []);
    const orgOwned = Boolean(selected?.scope?.organizationId);
    const clone = async () => { const data = await rulePacksApi.clone(selected._id, { name: `${selected.name} — organization copy` }); setMessage('Editable organization copy created.'); await load(); await select(data.pack._id); };
    const save = async () => { try { const rules = JSON.parse(rulesText); const data = await rulePacksApi.update(selected._id, { name: selected.name, description: selected.description, effectiveFrom: selected.effectiveFrom, rules, sources: selected.sources, changeNotes: selected.changeNotes }); setSelected(data.pack); setValidation(data.validation); setMessage('Draft saved.'); await load(); } catch (error: any) { setMessage(error?.response?.data?.error || error.message || 'Rules must be valid JSON.'); } };
    const validate = async () => { try { const data = await rulePacksApi.validate(selected._id); setValidation(data); setSelected(data.pack); setMessage('Validation passed.'); await load(); } catch (error: any) { setValidation(error?.response?.data); setMessage('Validation found issues that must be corrected.'); } };
    const publish = async () => { if (!window.confirm('Confirm jurisdictional review and publish this immutable version?')) return; const data = await rulePacksApi.publish(selected._id, { confirmReviewed: true, reviewedBy: 'Organization rule-pack reviewer' }); setSelected(data.pack); setMessage('Rule pack published and selected for new calculations. Approved history was not changed.'); await load(); };
    const simulate = async () => { const start = new Date(); start.setHours(0, 0, 0, 0); const end = new Date(start.getTime() + 6 * 86400000); const clockIn = new Date(start); clockIn.setHours(9); const clockOut = new Date(start); clockOut.setHours(18); const data = await rulePacksApi.simulate(selected._id, { startDate: start, endDate: end, timezone: 'UTC', entries: [{ entryType: 'clock_in', timestamp: clockIn }, { entryType: 'clock_out', timestamp: clockOut }] }); setSimulation(data); };
    const compare = async (id: string) => { setCompareId(id); if (!id) return setComparison(null); const data = await rulePacksApi.get(id); setComparison(data); };
    const correctionRun = async () => {
        const periodStart = window.prompt('Correction period start (YYYY-MM-DD)'); const periodEnd = window.prompt('Correction period end (YYYY-MM-DD)');
        const reason = window.prompt('Why should approved history be recalculated? This will create new adjustment versions.');
        if (!periodStart || !periodEnd || !reason) return;
        await correctionRunsApi.create({ type: 'rule_change', periodStart, periodEnd, reason, rulePackId: selected._id });
        setMessage('Audited correction run queued. Existing approved and payroll versions remain unchanged.');
    };

    return <div className="space-y-6">
        <div><h1 className="text-2xl font-semibold text-white">Rule Pack Studio</h1><p className="mt-1 text-sm text-zinc-400">Versioned, reviewable working-time rules with simulations and immutable publication.</p></div>
        {message && <div className="rounded-lg border border-teal-500/30 bg-teal-500/10 px-4 py-3 text-sm text-teal-200">{message}</div>}
        <div className="grid min-h-[680px] overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900/40 lg:grid-cols-[300px_minmax(0,1fr)]">
            <aside className="border-b border-zinc-800 lg:border-b-0 lg:border-r"><div className="border-b border-zinc-800 px-4 py-3 text-xs font-medium uppercase tracking-wide text-zinc-500">Available packs</div><div className="max-h-[640px] overflow-y-auto p-2">{packs.map(pack => <button key={pack._id} onClick={() => select(pack._id)} className={`mb-1 w-full rounded-lg px-3 py-3 text-left ${selected?._id === pack._id ? 'bg-zinc-800 text-white' : 'text-zinc-400 hover:bg-zinc-800/50 hover:text-zinc-200'}`}><div className="flex items-start justify-between gap-2"><div className="text-sm font-medium">{pack.name}</div><span className="text-[10px] uppercase text-zinc-500">v{pack.version}</span></div><div className="mt-1 flex gap-2 text-xs text-zinc-600"><span>{pack.jurisdiction?.countryCode || pack.jurisdiction?.regionCode || 'Global'}</span><span>·</span><span>{pack.status}</span></div></button>)}</div></aside>
            {selected ? <main className="p-5 lg:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><Scale className="h-5 w-5 text-teal-400" /><h2 className="text-lg font-semibold text-white">{selected.name}</h2></div><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-400">{selected.description || selected.changeNotes || 'No description supplied.'}</p><div className="mt-2 text-xs text-zinc-600">{selected.key} · version {selected.version} · {selected.status} · effective {new Date(selected.effectiveFrom).toLocaleDateString()}</div></div><div className="flex flex-wrap gap-2">{!orgOwned ? <button onClick={clone} className="inline-flex items-center gap-2 rounded-lg bg-teal-600 px-3 py-2 text-sm font-medium text-white"><Copy className="h-4 w-4" />Clone to edit</button> : <><button onClick={save} disabled={selected.status === 'published'} className="inline-flex items-center gap-2 rounded-lg border border-zinc-700 px-3 py-2 text-sm text-zinc-200 disabled:opacity-40"><Save className="h-4 w-4" />Save</button><button onClick={validate} disabled={selected.status === 'published'} className="inline-flex items-center gap-2 rounded-lg border border-zinc-700 px-3 py-2 text-sm text-zinc-200 disabled:opacity-40"><CheckCircle2 className="h-4 w-4" />Validate</button><button onClick={publish} disabled={!['validated', 'draft'].includes(selected.status)} className="inline-flex items-center gap-2 rounded-lg bg-teal-600 px-3 py-2 text-sm font-medium text-white disabled:opacity-40"><Send className="h-4 w-4" />Publish</button></>}</div></div>
                <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><div><label className="text-xs font-medium uppercase tracking-wide text-zinc-500">Rules JSON</label><textarea value={rulesText} onChange={e => setRulesText(e.target.value)} readOnly={!orgOwned || selected.status === 'published'} spellCheck={false} className="mt-2 h-[430px] w-full resize-y rounded-lg border border-zinc-700 bg-zinc-950 p-4 font-mono text-xs leading-6 text-zinc-200 read-only:text-zinc-500" />{validation && <div className={`mt-3 rounded-lg border px-3 py-2 text-xs ${validation.valid ? 'border-teal-500/30 bg-teal-500/10 text-teal-300' : 'border-amber-500/30 bg-amber-500/10 text-amber-300'}`}>{validation.valid ? 'Schema and rule validation passed.' : (validation.errors || []).map((error: any) => error.message || error).join(' · ')}</div>}</div>
                <aside className="space-y-5"><div className="rounded-lg border border-zinc-800 bg-zinc-950/50 p-4"><h3 className="text-sm font-semibold text-white">Impact preview</h3><p className="mt-1 text-xs leading-5 text-zinc-500">Runs a sample 09:00–18:00 day through this exact version. It never writes timesheets.</p><button onClick={simulate} className="mt-3 inline-flex items-center gap-2 text-sm font-medium text-teal-400"><Beaker className="h-4 w-4" />Run simulation</button>{simulation && <div className="mt-3 text-xs leading-5 text-zinc-400">Regular: {simulation.result?.totals?.regularHours ?? 0}h<br />Overtime: {simulation.result?.totals?.overtimeHours ?? 0}h<br />Exceptions: {simulation.result?.totals?.exceptionCount ?? simulation.result?.dailyEntries?.flatMap((d: any) => d.exceptions || []).length ?? 0}</div>}</div>
                <div className="rounded-lg border border-zinc-800 bg-zinc-950/50 p-4"><h3 className="text-sm font-semibold text-white">Compare effective rules</h3><select value={compareId} onChange={e => compare(e.target.value)} className="mt-3 w-full rounded-md border border-zinc-700 bg-zinc-900 px-2 py-2 text-xs"><option value="">Choose another pack</option>{packs.filter(p => p._id !== selected._id).map(p => <option key={p._id} value={p._id}>{p.name} v{p.version}</option>)}</select>{comparison && <div className="mt-3 max-h-40 overflow-auto whitespace-pre-wrap font-mono text-[10px] leading-5 text-zinc-500">{JSON.stringify(comparison.resolved?.rules || {}, null, 2)}</div>}</div>
                <div className="rounded-lg border border-zinc-800 bg-zinc-950/50 p-4"><h3 className="text-sm font-semibold text-white">Sources and review</h3><div className="mt-3 space-y-3">{selected.sources?.length ? selected.sources.map((source: any, index: number) => <div key={index} className="text-xs text-zinc-400">{source.url ? <a href={source.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-teal-400 hover:underline">{source.title}<ExternalLink className="h-3 w-3" /></a> : source.title}<p className="mt-1 leading-5 text-zinc-600">{source.note}</p></div>) : <p className="text-xs text-amber-300">No source references. Add current authoritative sources before validation.</p>}</div><p className="mt-4 border-t border-zinc-800 pt-3 text-[11px] leading-5 text-zinc-600">Seeded packs are implementation templates. Publication requires documented jurisdictional review. Approved history is never recalculated automatically.</p>{selected.status === 'published' && orgOwned && <button onClick={correctionRun} className="mt-3 text-xs font-medium text-amber-300 hover:text-amber-200">Launch audited history correction…</button>}</div></aside></div>
            </main> : <div className="p-12 text-center text-zinc-500">Choose a rule pack.</div>}
        </div>
    </div>;
}
