import type { ActionDescriptor, EventDescriptor, RecipeTemplate } from "./domain.js";

export const eventCatalog: EventDescriptor[] = [
  {
    id: "workspace.message_reaction_added.v1",
    product: "Workspace",
    label: "Reaction added to a message",
    description: "A human added a configured reaction to a Workspace message.",
    subjectType: "workspace_message",
    schemaVersion: 1,
    output: { messageId: "string", channelId: "string", permalink: "string", excerpt: "string", reaction: "string", actorId: "string" },
    dataClass: "internal",
    externalEligible: false,
  },
  {
    id: "boards.card_moved.v1",
    product: "Boards",
    label: "Board card moved",
    description: "A Board card entered a configured status.",
    subjectType: "board_card",
    schemaVersion: 1,
    output: { cardId: "string", boardId: "string", title: "string", status: "string", projectChannelId: "string", projectPageId: "string" },
    dataClass: "internal",
    externalEligible: false,
  },
  {
    id: "identity.employee_membership_activated.v1",
    product: "Identity",
    label: "Employee membership activated",
    description: "Seemplify Identity activated a verified organization membership and application grants.",
    subjectType: "membership",
    schemaVersion: 1,
    output: { employeeId: "string", employeeName: "string", employeeEmail: "string", onboardingTemplateId: "string" },
    dataClass: "confidential",
    externalEligible: false,
  },
  {
    id: "leave.request_submitted.v1",
    product: "Leave",
    label: "Leave request submitted",
    description: "Leave accepted a valid request and reserved the current balance.",
    subjectType: "leave_request",
    schemaVersion: 1,
    output: { requestId: "string", requestRevision: "string", employeeId: "string", approverId: "string", leaveType: "string", startsAt: "string", endsAt: "string", teamChannelId: "string" },
    dataClass: "restricted",
    externalEligible: false,
  },
  {
    id: "payroll.run_ready_for_review.v1",
    product: "Payroll",
    label: "Payroll run ready for review",
    description: "Payroll calculated and validated a run revision that is ready for exact approval.",
    subjectType: "payroll_run",
    schemaVersion: 1,
    output: { runId: "string", runRevision: "string", totalsHash: "string", period: "string", currency: "string", total: "number", reviewerId: "string" },
    dataClass: "restricted",
    externalEligible: false,
  },
  {
    id: "pages.page_published.v1",
    product: "Pages",
    label: "Page published",
    description: "A classified Page revision was published.",
    subjectType: "page",
    schemaVersion: 1,
    output: { pageId: "string", revision: "string", title: "string", content: "string", classification: "string", folderId: "string" },
    dataClass: "internal",
    externalEligible: true,
  },
  {
    id: "external.webhook_received.v1",
    product: "Developer Platform",
    label: "Incoming webhook received",
    description: "A verified installed application posted to a scoped incoming webhook.",
    subjectType: "external_event",
    schemaVersion: 1,
    output: { source: "string", type: "string", data: "object" },
    dataClass: "internal",
    externalEligible: true,
  },
];

export const actionCatalog: ActionDescriptor[] = [
  {
    id: "boards.create_card.v1", product: "Boards", label: "Create Board card",
    description: "Create a card through Boards and return its authoritative link.",
    subjectTypes: ["workspace_message", "membership", "external_event"],
    input: { boardId: "string", title: "string", description: "string", sourceUrl: "string" },
    risk: "R1", requiredRoles: ["member", "manager", "admin", "owner"], requiredApps: ["messaging"],
    approvalRequired: false, makerChecker: false, external: false, emittedEvent: "boards.card_created.v1",
    dataClasses: ["internal", "confidential"], idempotent: true,
  },
  {
    id: "workspace.reply_in_thread.v1", product: "Workspace", label: "Reply in message thread",
    description: "Post a bounded reply to the originating Workspace thread.",
    subjectTypes: ["workspace_message"], input: { channelId: "string", messageId: "string", text: "string" },
    risk: "R1", requiredRoles: ["member", "manager", "admin", "owner"], requiredApps: ["messaging"],
    approvalRequired: false, makerChecker: false, external: false, emittedEvent: "workspace.message_posted.v1",
    dataClasses: ["internal", "confidential"], idempotent: true,
  },
  {
    id: "workspace.send_message.v1", product: "Workspace", label: "Send Workspace message",
    description: "Send a bounded message to a configured channel or user.",
    subjectTypes: ["board_card", "leave_request", "payroll_run", "membership", "external_event"],
    input: { destinationId: "string", text: "string", visibility: "string" },
    risk: "R1", requiredRoles: ["member", "manager", "admin", "owner"], requiredApps: ["messaging"],
    approvalRequired: false, makerChecker: false, external: false, emittedEvent: "workspace.message_posted.v1",
    dataClasses: ["public", "internal", "confidential"], idempotent: true,
  },
  {
    id: "pages.append_activity.v1", product: "Pages", label: "Append Page activity",
    description: "Append a linked activity record to a mapped project Page.",
    subjectTypes: ["board_card"], input: { pageId: "string", text: "string", sourceUrl: "string" },
    risk: "R1", requiredRoles: ["member", "manager", "admin", "owner"], requiredApps: ["messaging"],
    approvalRequired: false, makerChecker: false, external: false, emittedEvent: "pages.activity_appended.v1",
    dataClasses: ["internal"], idempotent: true,
  },
  {
    id: "workspace.setup_employee_channels.v1", product: "Workspace", label: "Set up employee channels",
    description: "Assign only the channels allowed by the employee's verified grants.",
    subjectTypes: ["membership"], input: { employeeId: "string", templateId: "string" },
    risk: "R1", requiredRoles: ["admin", "owner"], requiredApps: ["messaging"],
    approvalRequired: false, makerChecker: false, external: false, emittedEvent: "workspace.employee_channels_ready.v1",
    dataClasses: ["confidential"], idempotent: true,
  },
  {
    id: "boards.create_onboarding_board.v1", product: "Boards", label: "Create onboarding Board",
    description: "Create the reviewed onboarding checklist without changing identity membership.",
    subjectTypes: ["membership"], input: { employeeId: "string", employeeName: "string", templateId: "string" },
    risk: "R1", requiredRoles: ["admin", "owner"], requiredApps: ["messaging"],
    approvalRequired: false, makerChecker: false, external: false, emittedEvent: "boards.onboarding_board_created.v1",
    dataClasses: ["confidential"], idempotent: true,
  },
  {
    id: "pages.create_onboarding_page.v1", product: "Pages", label: "Create onboarding Page",
    description: "Create an employee-specific onboarding Page from an approved template.",
    subjectTypes: ["membership"], input: { employeeId: "string", employeeName: "string", templateId: "string" },
    risk: "R1", requiredRoles: ["admin", "owner"], requiredApps: ["messaging"],
    approvalRequired: false, makerChecker: false, external: false, emittedEvent: "pages.onboarding_page_created.v1",
    dataClasses: ["confidential"], idempotent: true,
  },
  {
    id: "learning.assign_required_courses.v1", product: "Learning", label: "Assign required courses",
    description: "Assign courses permitted by the activated membership and onboarding template.",
    subjectTypes: ["membership"], input: { employeeId: "string", templateId: "string" },
    risk: "R1", requiredRoles: ["admin", "owner"], requiredApps: ["seemplify-learning"],
    approvalRequired: false, makerChecker: false, external: false, emittedEvent: "learning.courses_assigned.v1",
    dataClasses: ["confidential"], idempotent: true,
  },
  {
    id: "leave.record_decision.v1", product: "Leave", label: "Record leave decision",
    description: "Ask Leave to recheck policy, balance, request revision, and approver before recording a decision.",
    subjectTypes: ["leave_request"], input: { requestId: "string", requestRevision: "string", decision: "string", approvalId: "string", rationale: "string" },
    risk: "R3", requiredRoles: ["manager", "admin", "owner"], requiredApps: ["leave-management"],
    approvalRequired: true, makerChecker: true, external: false, emittedEvent: "leave.request_approved.v1",
    dataClasses: ["restricted"], idempotent: true,
  },
  {
    id: "time.block_expected_absence.v1", product: "Time & Attendance", label: "Block expected absence",
    description: "Record an expected absence only after Leave confirms approval.",
    subjectTypes: ["leave_request"], input: { employeeId: "string", startsAt: "string", endsAt: "string", leaveRequestId: "string", decisionOutcomeId: "string" },
    risk: "R2", requiredRoles: ["manager", "admin", "owner"], requiredApps: ["time-attendance"],
    approvalRequired: false, makerChecker: false, external: false, emittedEvent: "time.expected_absence_blocked.v1",
    dataClasses: ["confidential", "restricted"], idempotent: true,
  },
  {
    id: "payroll.finalize_run.v1", product: "Payroll", label: "Finalize payroll run",
    description: "Finalize the exact reviewed Payroll revision and totals hash after maker-checker approval.",
    subjectTypes: ["payroll_run"], input: { runId: "string", runRevision: "string", totalsHash: "string", approvalId: "string" },
    risk: "R3", requiredRoles: ["admin", "owner"], requiredApps: ["payroll-management"],
    approvalRequired: true, makerChecker: true, external: false, emittedEvent: "payroll.run_finalized.v1",
    dataClasses: ["restricted"], idempotent: true,
  },
  {
    id: "google-drive.upsert_page.v1", product: "Google Drive", label: "Create or update Drive document",
    description: "Sync an allowed Page revision through the organization's Nango connection.",
    subjectTypes: ["page"], input: { pageId: "string", title: "string", content: "string", folderId: "string" },
    risk: "R2", requiredRoles: ["admin", "owner"], requiredApps: ["messaging"],
    approvalRequired: false, makerChecker: false, external: true, provider: "google-drive", emittedEvent: "external.google_drive_page_synced.v1",
    dataClasses: ["public", "internal"], idempotent: true,
  },
  {
    id: "gmail.send_message.v1", product: "Gmail", label: "Send Gmail message",
    description: "Send an explicitly addressed email through an installed Nango Gmail connection.",
    subjectTypes: ["external_event", "board_card", "membership"], input: { to: "string", subject: "string", text: "string" },
    risk: "R2", requiredRoles: ["admin", "owner"], requiredApps: [],
    approvalRequired: false, makerChecker: false, external: true, provider: "google-mail", emittedEvent: "external.gmail_message_sent.v1",
    dataClasses: ["public", "internal", "confidential"], idempotent: true,
  },
];

export const recipeTemplates: RecipeTemplate[] = [
  {
    id: "reaction-to-board-task", category: "Workspace", name: "Reaction to Board task",
    description: "Create a Board card from an 👀 reaction and reply with the authoritative card link.",
    definition: {
      name: "Reaction to Board task", description: "Turn a reviewed Workspace reaction into a traceable Board task.",
      trigger: { eventId: "workspace.message_reaction_added.v1" }, enabled: true, maximumRunsPerHour: 120,
      steps: [
        { id: "create-card", type: "action", actionId: "boards.create_card.v1", input: { boardId: "inbox", title: "$event.payload.excerpt", description: "Created from Workspace", sourceUrl: "$event.payload.permalink" } },
        { id: "reply", type: "action", actionId: "workspace.reply_in_thread.v1", input: { channelId: "$event.payload.channelId", messageId: "$event.payload.messageId", text: "Board task created: {{$steps.create-card.output.url}}" } },
      ],
    },
  },
  {
    id: "board-done-to-project-update", category: "Workspace", name: "Board completion update",
    description: "Tell the mapped project channel and append the result to its Page when a card reaches done.",
    definition: {
      name: "Board completion update", description: "Reflect Board completion in the mapped communication surfaces.",
      trigger: { eventId: "boards.card_moved.v1" }, enabled: true, maximumRunsPerHour: 200,
      steps: [
        { id: "notify", type: "action", actionId: "workspace.send_message.v1", input: { destinationId: "$event.payload.projectChannelId", text: "Completed: {{$event.payload.title}}", visibility: "channel" } },
        { id: "page", type: "action", actionId: "pages.append_activity.v1", input: { pageId: "$event.payload.projectPageId", text: "Completed: {{$event.payload.title}}", sourceUrl: "$steps.notify.output.url" } },
      ],
    },
  },
  {
    id: "employee-onboarding", category: "People", name: "Employee onboarding",
    description: "Set up Workspace, Boards, Pages, and Learning only after Identity activates the membership.",
    definition: {
      name: "Employee onboarding", description: "Create the employee's permitted onboarding resources from one authoritative Identity event.",
      trigger: { eventId: "identity.employee_membership_activated.v1" }, enabled: true, maximumRunsPerHour: 50,
      steps: [
        { id: "channels", type: "action", actionId: "workspace.setup_employee_channels.v1", input: { employeeId: "$event.payload.employeeId", templateId: "$event.payload.onboardingTemplateId" } },
        { id: "board", type: "action", actionId: "boards.create_onboarding_board.v1", input: { employeeId: "$event.payload.employeeId", employeeName: "$event.payload.employeeName", templateId: "$event.payload.onboardingTemplateId" } },
        { id: "page", type: "action", actionId: "pages.create_onboarding_page.v1", input: { employeeId: "$event.payload.employeeId", employeeName: "$event.payload.employeeName", templateId: "$event.payload.onboardingTemplateId" } },
        { id: "courses", type: "action", actionId: "learning.assign_required_courses.v1", input: { employeeId: "$event.payload.employeeId", templateId: "$event.payload.onboardingTemplateId" } },
      ],
    },
  },
  {
    id: "payroll-review", category: "Finance", name: "Payroll review and finalization",
    description: "Request exact maker-checker approval before Payroll revalidates and finalizes a run.",
    definition: {
      name: "Payroll review and finalization", description: "Finalize only the exact Payroll revision and totals hash that a different eligible reviewer approved.",
      trigger: { eventId: "payroll.run_ready_for_review.v1" }, enabled: true, maximumRunsPerHour: 20,
      steps: [
        { id: "review", type: "approval", purpose: "Finalize this exact payroll run revision", approverRoles: ["admin", "owner"], expiresInHours: 24 },
        { id: "finalize", type: "action", actionId: "payroll.finalize_run.v1", input: { runId: "$event.payload.runId", runRevision: "$event.payload.runRevision", totalsHash: "$event.payload.totalsHash", approvalId: "$approval.id" } },
      ],
    },
  },
  {
    id: "leave-review", category: "People", name: "Leave review and team update",
    description: "Bind the decision to the exact Leave request, then send only a bounded team notice.",
    definition: {
      name: "Leave review and team update", description: "Keep Leave authoritative while coordinating Time and Workspace side effects.",
      trigger: { eventId: "leave.request_submitted.v1" }, enabled: true, maximumRunsPerHour: 80,
      steps: [
        { id: "review", type: "approval", purpose: "Decide this exact leave request revision", approverRoles: ["manager", "admin", "owner"], expiresInHours: 72,
          onReject: { id: "record-rejection", type: "action", actionId: "leave.record_decision.v1", input: { requestId: "$event.payload.requestId", requestRevision: "$event.payload.requestRevision", decision: "rejected", approvalId: "$approval.id", rationale: "$approval.rationale" } } },
        { id: "decision", type: "action", actionId: "leave.record_decision.v1", input: { requestId: "$event.payload.requestId", requestRevision: "$event.payload.requestRevision", decision: "approved", approvalId: "$approval.id", rationale: "Approved in Automation Hub" } },
        { id: "absence", type: "action", actionId: "time.block_expected_absence.v1", input: { employeeId: "$event.payload.employeeId", startsAt: "$event.payload.startsAt", endsAt: "$event.payload.endsAt", leaveRequestId: "$event.payload.requestId", decisionOutcomeId: "$steps.decision.output.outcomeId" } },
        { id: "notice", type: "action", actionId: "workspace.send_message.v1", input: { destinationId: "$event.payload.teamChannelId", text: "An approved team absence has been added to the schedule.", visibility: "channel" } },
      ],
    },
  },
  {
    id: "page-to-drive", category: "External", name: "Published Page to Google Drive",
    description: "Sync public or internal Pages to an installed organization Drive connection.",
    definition: {
      name: "Published Page to Google Drive", description: "Create or update a Drive document while retaining the provider mapping.",
      trigger: { eventId: "pages.page_published.v1" }, enabled: true, maximumRunsPerHour: 60,
      steps: [
        { id: "drive", type: "action", actionId: "google-drive.upsert_page.v1", input: { pageId: "$event.payload.pageId", title: "$event.payload.title", content: "$event.payload.content", folderId: "$event.payload.folderId" } },
      ],
    },
  },
];

export const connectorCatalog = [
  { provider: "google-mail", label: "Gmail", description: "Messages, drafts, labels, threads, and mailbox triggers.", reviewed: true },
  { provider: "google-calendar", label: "Google Calendar", description: "Calendar events and availability.", reviewed: false },
  { provider: "google-drive", label: "Google Drive", description: "Files and Page publication targets.", reviewed: true },
  { provider: "slack", label: "Slack", description: "Channels, messages, users, and external triggers.", reviewed: false },
  { provider: "microsoft-teams", label: "Microsoft Teams", description: "Teams and Microsoft Graph messaging workflows.", reviewed: false },
  { provider: "notion", label: "Notion", description: "Pages, databases, blocks, and knowledge sync.", reviewed: false },
] as const;

export const commandCatalog = [
  { command: "/automations", label: "Open Automation Hub", internal: true, requiredRole: "member" },
  { command: "/create-task", label: "Create a Board task from this message", internal: true, requiredRole: "member" },
  { command: "/request-leave", label: "Open a Leave request", internal: true, requiredRole: "member" },
  { command: "/review-payroll", label: "Open the authoritative Payroll review", internal: true, requiredRole: "admin" },
  { command: "/gmail-send", label: "Send through an installed Gmail connection", internal: false, provider: "google-mail", requiredRole: "admin" },
] as const;
