import { expect,test,type Page,type Route } from '@playwright/test';
const password='Playwright-Test-Password-2026!';const stamp='2026-08-07T10:00:00.000Z';const sha='a'.repeat(64);
const policy={enabled:true,purpose:'journey_churn_decision_support',minimumTrainingSamples:1000,minimumClassSamples:100,minimumValidationSamples:200,minimumAreaUnderRoc:.7,maximumBrierScore:.25,maximumPopulationStabilityIndex:.2,maximumMissingFeatureRatio:.1,maximumOutOfDistributionScore:10};
const summary={id:'churn-v1',target:'churn',name:'Reviewed churn model',state:'approved',revision:1,currentVersionId:'version-1',createdAt:stamp,updatedAt:stamp};
const evidence={id:'churn-v1',target:'churn',version:'1.0.0',state:'approved',trainingWindow:{from:'2025-01-01T00:00:00.000Z',to:'2025-07-01T00:00:00.000Z'},validationWindow:{from:'2025-07-01T00:00:00.000Z',to:'2025-09-01T00:00:00.000Z'},trainingSamples:2000,positiveSamples:700,negativeSamples:1300,validationSamples:500,areaUnderRoc:.82,brierScore:.14,featureNames:['recent_complaints'],trainedByUserId:'trainer',approvedByUserId:'owner',approvedAt:stamp,contentSha256:sha};
const detail={model:summary,versions:[{id:'version-1',model:evidence,contentSha256:sha,approvedAt:stamp}]};
const record={target:'churn',policy,revision:1,updatedAt:stamp};const conversion={...record,target:'conversion',policy:{...policy,purpose:'journey_conversion_decision_support'}};
const result={decision:'abstained',target:'churn',modelId:'churn-v1',modelVersion:'1.0.0',modelContentSha256:sha,subjectRefSha256:'b'.repeat(64),sourceWindow:{from:stamp,to:'2026-08-08T10:00:00.000Z'},score:null,confidence:null,reasonCodes:['DRIFT_EVIDENCE_MISSING'],limitations:['A probability is decision support, not proof of a future customer outcome.'],explanation:[]};
const run={id:'run-1',modelId:'churn-v1',modelVersionId:'version-1',evaluatorKind:'governed_fixture',evaluatorOutputSha256:'c'.repeat(64),result,resultSha256:'d'.repeat(64),createdAt:stamp};
function json(route:Route,value:unknown,status=200){return route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});}
async function signIn(page:Page,role:'manager'|'member'){await page.route('**/api/auth/session',async route=>{const response=await route.fetch();const body=await response.json();if(body?.authenticated&&body.subscription?.features){body.subscription.features.journeyActualPaths=true;if(body.activeSpace)body.activeSpace.role=role==='manager'?'owner':'member';}await route.fulfill({response,json:body});});await page.goto('/login');await page.getByLabel('Email').fill('qa@seemplify.local');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL('/');}
async function fixtures(page:Page){let runs=[run];await page.route(/\/api\/journey-predictive-governance(?:\/.*)?$/,route=>{const url=new URL(route.request().url());const method=route.request().method();if(url.pathname.endsWith('/runs'))return json(route,{runs});if(url.pathname.endsWith('/models/churn-v1'))return json(route,detail);if(url.pathname.endsWith('/policies/churn')&&method==='PUT')return json(route,{...record,revision:2});if(url.pathname.includes('/drift-evaluations'))return json(route,{id:'drift-1',modelId:'churn-v1',modelVersionId:'version-1',decision:'within_envelope',reasonCodes:[],evaluatedAt:stamp},201);if(url.pathname.endsWith('/evaluations')&&method==='POST'){runs=[run];return json(route,{id:'run-1',result,evaluatorKind:'governed_fixture',evaluatorOutputSha256:'c'.repeat(64),createdAt:stamp},201);}if(url.pathname.endsWith('/journey-predictive-governance'))return json(route,{models:[summary],policies:[record,conversion]});return json(route,{error:`Unhandled ${method} ${url.pathname}`},500);});}
test('manager reviews exact evidence, saves policy, records drift and fixture output',async({page})=>{await fixtures(page);await signIn(page,'manager');await page.goto('/journey-predictive-governance');await expect(page.getByRole('heading',{name:'Predictive governance'})).toBeVisible();await expect(page.getByText('No training or live inference.')).toBeVisible();await expect(page.getByText('Reviewed churn model')).toBeVisible();await expect(page.getByText(/AUROC 0.82/)).toBeVisible();await page.getByRole('button',{name:'Save policy revision'}).first().click();await page.locator('form').filter({hasText:'Record drift evaluation'}).locator('input[name="psi"]').fill('0.08');await page.locator('form').filter({hasText:'Record drift evaluation'}).locator('input[name="missing"]').fill('0');await page.locator('form').filter({hasText:'Record drift evaluation'}).locator('input[name="ood"]').fill('2');await page.getByRole('button',{name:'Record drift evidence'}).click();await expect(page.getByText('Abstained',{exact:true})).toBeVisible();await expect(page.getByTestId('journey-predictive-governance-workspace')).toBeVisible();});
test('member sees content-safe records and no mutation forms on desktop or mobile',async({page})=>{await fixtures(page);await signIn(page,'member');await page.goto('/journey-predictive-governance');await expect(page.getByText(/Read-only: members/)).toBeVisible();await expect(page.getByRole('heading',{name:'Approve a model version'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Save policy revision'})).toHaveCount(0);await expect(page.getByText('Drift Evidence Missing')).toBeVisible();await expect(page.getByText('customer-secret')).toHaveCount(0);await expect(page.getByTestId('journey-predictive-governance-workspace')).toBeVisible();});
