'use client';

import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { AlertCircle as CircleAlert, Edit2 as FilePenLine, ShieldCheck } from 'lucide-react';
import { exceptionsApi } from '@/lib/api';
import { useAuth } from '@/context/AuthContext';

export default function ExceptionsPage() {
    const params = useSearchParams(); const { user } = useAuth();
    const [items, setItems] = useState<any[]>([]); const [disclaimer, setDisclaimer] = useState(''); const [filter, setFilter] = useState('all'); const [message, setMessage] = useState(''); const [editing, setEditing] = useState<any>(null); const [explanation, setExplanation] = useState('');
    const targetUserId = params.get('userId') || undefined;
    const load = async () => { const data = await exceptionsApi.list({ status: filter, userId: targetUserId }); setItems(data.exceptions || []); setDisclaimer(data.disclaimer); };
    useEffect(() => { void load().catch(() => setMessage('Exceptions could not be loaded.')); }, [filter, targetUserId]);
    const submit = async () => { if (!editing || !explanation.trim()) return; await exceptionsApi.requestCorrection(editing._id, { explanation, evidence: [] }); setEditing(null); setExplanation(''); setMessage('Correction request submitted with a full audit trail.'); await load(); };
    const review = async (id: string, accepted: boolean) => { const note = window.prompt(accepted ? 'Review note and correction instructions' : 'Explain why the request was not accepted') || ''; await exceptionsApi.review(id, accepted, note); await load(); };
    const ownView = !targetUserId || targetUserId === user?.id;
    return <div className="space-y-6">
        <div><h1 className="text-2xl font-semibold text-white">Attendance exceptions</h1><p className="mt-1 text-sm text-zinc-400">Clear rule flags, employee explanations and version-safe corrections.</p></div>
        <div className="flex items-start gap-3 rounded-xl border border-zinc-800 bg-zinc-900/50 p-4"><ShieldCheck className="mt-0.5 h-5 w-5 text-teal-400" /><p className="text-sm leading-6 text-zinc-400">{disclaimer || 'Exceptions are review flags only and never make automatic employment decisions.'}</p></div>
        {message && <div className="rounded-lg border border-teal-500/30 bg-teal-500/10 px-4 py-3 text-sm text-teal-200">{message}</div>}
        <div className="flex flex-wrap gap-2">{['all', 'open', 'correction_requested', 'resolved'].map(value => <button key={value} onClick={() => setFilter(value)} className={`rounded-md px-3 py-1.5 text-xs capitalize ${filter === value ? 'bg-zinc-700 text-white' : 'border border-zinc-800 text-zinc-400 hover:bg-zinc-900'}`}>{value.replace('_', ' ')}</button>)}</div>
        <section className="overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900/50">{items.length ? items.map(item => <div key={item._id} className="border-b border-zinc-800 px-5 py-5 last:border-0"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><CircleAlert className={`mt-0.5 h-4 w-4 ${item.severity === 'high' ? 'text-amber-400' : 'text-zinc-500'}`} /><div><div className="text-sm font-medium capitalize text-white">{item.type.replaceAll('_', ' ')}</div><p className="mt-1 text-sm leading-6 text-zinc-400">{item.explanation?.message || item.description || 'This attendance record matched the configured exception rule.'}</p><div className="mt-2 text-xs text-zinc-600">{new Date(item.occurrenceDate).toLocaleDateString()} · Rule {item.rule?.code || item.ruleCode || 'configured policy'} · {item.status.replace('_', ' ')}</div></div></div><div>{ownView && item.status === 'open' && <button onClick={() => setEditing(item)} className="inline-flex items-center gap-2 rounded-md border border-zinc-700 px-3 py-1.5 text-xs text-zinc-300 hover:bg-zinc-800"><FilePenLine className="h-3.5 w-3.5" />Request correction</button>}{!ownView && item.status === 'correction_requested' && <div className="flex gap-2"><button onClick={() => review(item._id, true)} className="rounded-md border border-teal-500/40 px-3 py-1.5 text-xs text-teal-300">Accept</button><button onClick={() => review(item._id, false)} className="rounded-md border border-zinc-700 px-3 py-1.5 text-xs text-zinc-400">Reject</button></div>}</div></div>{item.correctionRequest?.explanation && <div className="mt-4 ml-7 rounded-lg border border-zinc-800 bg-zinc-950/60 p-3 text-sm text-zinc-300"><span className="text-xs font-medium text-zinc-500">Employee explanation</span><p className="mt-1 leading-6">{item.correctionRequest.explanation}</p></div>}</div>) : <div className="p-12 text-center text-sm text-zinc-500">No exceptions match this filter.</div>}</section>
        {editing && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/75 p-4"><div className="w-full max-w-lg rounded-xl border border-zinc-700 bg-zinc-950 p-6 shadow-2xl"><h2 className="text-base font-semibold text-white">Explain the correction</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Describe what happened and the change you are requesting. Accepted requests still use an immutable, versioned timesheet adjustment.</p><textarea autoFocus value={explanation} onChange={e => setExplanation(e.target.value)} rows={6} className="mt-4 w-full rounded-lg border border-zinc-700 bg-zinc-900 p-3 text-sm text-white" /><div className="mt-4 flex justify-end gap-2"><button onClick={() => setEditing(null)} className="rounded-lg px-3 py-2 text-sm text-zinc-400">Cancel</button><button onClick={submit} className="rounded-lg bg-teal-600 px-4 py-2 text-sm font-medium text-white">Submit request</button></div></div></div>}
    </div>;
}
