import { useEffect, useState } from 'react';
import { BarChart3 } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '@/lib/api';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { EmptyState } from '@/components/EmptyState';
import type { Survey } from '@/types';

type Analytics = { totals: { responses: number; completed: number; partial: number; completionRate: number; averageDurationSeconds: number | null; analyzedResponses: number }; metrics: { nps: number | null; promoters: number; passives: number; detractors: number; csat: number | null; ces: number | null }; trend: { date: string; responses: number; score: number | null }[]; questions: { questionId: string; title: string; answered: number; responseRate: number; average: number | null; distribution: { label: string; count: number }[] }[]; drivers: { title: string; correlation: number; sampleSize: number }[]; sentiment: Record<string, number>; themes: { name: string; count: number }[]; dropoff: { title: string; reached: number }[] };

export function AnalyticsTab({ survey, refreshKey }: { survey: Survey; refreshKey: number }) {
  const [data, setData] = useState<Analytics | null>(null);
  useEffect(() => { api<Analytics>(`/api/surveys/${survey.id}/analytics`).then(setData); }, [survey.id, refreshKey]);
  if (!data) return <div className="h-72 animate-pulse bg-muted" />;
  if (!data.totals.responses) return <EmptyState icon={BarChart3} title="Analytics begin with the first response" description="The dashboard will calculate completion, experience metrics, distributions, drop-off, sentiment, and key drivers." />;
  const sentiment = Object.entries(data.sentiment).map(([name, value]) => ({ name: name.replaceAll('_', ' '), value }));
  return <div className="space-y-5">
    <div className="grid overflow-hidden rounded-lg border bg-card sm:grid-cols-2 lg:grid-cols-5 lg:divide-x">{[
      ['Responses', data.totals.responses], ['Completion', `${data.totals.completionRate}%`], ['NPS', data.metrics.nps ?? '—'], ['CSAT', data.metrics.csat == null ? '—' : data.metrics.csat.toFixed(1)], ['Analysed', data.totals.analyzedResponses]
    ].map(([label, value]) => <div className="border-b p-4 last:border-b-0 sm:border-b lg:border-b-0" key={label}><div className="text-xs font-medium text-muted-foreground">{label}</div><div className="mt-2 text-2xl font-semibold tracking-tight">{value}</div></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>Response trend</CardTitle></CardHeader><CardContent><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.trend}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" tickLine={false} axisLine={false} fontSize={11} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} fontSize={11} /><Tooltip /><Line dataKey="responses" stroke="hsl(var(--primary))" strokeWidth={2} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle>Sentiment from Terra</CardTitle></CardHeader><CardContent><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={sentiment} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" allowDecimals={false} tickLine={false} axisLine={false} /><YAxis type="category" dataKey="name" width={90} tickLine={false} axisLine={false} fontSize={11} /><Tooltip /><Bar dataKey="value" fill="hsl(var(--primary))" radius={[0, 3, 3, 0]} /></BarChart></ResponsiveContainer></div></CardContent></Card></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><Card><CardHeader><CardTitle>Question performance</CardTitle></CardHeader><CardContent className="px-0 pb-0"><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Question</th><th>Answered</th><th>Rate</th><th>Average</th><th>Most common</th></tr></thead><tbody>{data.questions.map((item) => <tr key={item.questionId}><td className="max-w-sm font-medium">{item.title}</td><td>{item.answered}</td><td>{item.responseRate}%</td><td>{item.average == null ? '—' : item.average.toFixed(2)}</td><td>{item.distribution[0]?.label || '—'}</td></tr>)}</tbody></table></div></CardContent></Card><div className="space-y-5"><Card><CardHeader><CardTitle>Key drivers</CardTitle></CardHeader><CardContent>{data.drivers.length ? <div className="space-y-4">{data.drivers.slice(0, 6).map((item) => <div key={item.title}><div className="flex justify-between gap-3 text-sm"><span className="line-clamp-1">{item.title}</span><span className="font-mono text-xs">{item.correlation.toFixed(2)}</span></div><div className="mt-1.5 h-1.5 bg-muted"><div className="h-full bg-primary" style={{ width: `${Math.abs(item.correlation) * 100}%` }} /></div><div className="mt-1 text-[11px] text-muted-foreground">n={item.sampleSize}</div></div>)}</div> : <p className="text-sm text-muted-foreground">At least three paired numeric responses are required.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Leading themes</CardTitle></CardHeader><CardContent>{data.themes.length ? <div className="flex flex-wrap gap-2">{data.themes.map((item) => <span className="border bg-muted/30 px-2.5 py-1.5 text-xs" key={item.name}>{item.name} · {item.count}</span>)}</div> : <p className="text-sm text-muted-foreground">Themes appear as Terra analyses open text.</p>}</CardContent></Card></div></div>
  </div>;
}
