import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import type { Survey } from '@/types';

export function SettingsTab({ survey, onChange }: { survey: Survey; onChange: (survey: Survey) => void }) {
  const set = (values: Partial<Survey>) => onChange({ ...survey, ...values });
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><Card><CardHeader><CardTitle>Survey details</CardTitle><CardDescription>These details guide respondents and contextualise analysis.</CardDescription></CardHeader><CardContent className="space-y-4"><div><Label className="field-label">Title</Label><Input value={survey.title} onChange={(event) => set({ title: event.target.value })} /></div><div><Label className="field-label">Description</Label><Textarea rows={4} value={survey.description} onChange={(event) => set({ description: event.target.value })} /></div><div className="grid gap-4 sm:grid-cols-2"><div><Label className="field-label">Programme</Label><select className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm" value={survey.purpose} onChange={(event) => set({ purpose: event.target.value as Survey['purpose'] })}><option value="customer_experience">Customer experience</option><option value="employee_experience">Employee experience</option><option value="market_research">Market research</option></select></div><div><Label className="field-label">Primary metric</Label><select className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm" value={survey.primaryMetric} onChange={(event) => set({ primaryMetric: event.target.value as Survey['primaryMetric'] })}><option value="nps">NPS</option><option value="csat">CSAT</option><option value="ces">CES</option><option value="custom">Custom</option></select></div></div><div className="grid gap-4 sm:grid-cols-2"><div><Label className="field-label">Audience</Label><Input value={survey.audience} onChange={(event) => set({ audience: event.target.value })} /></div><div><Label className="field-label">Language</Label><Input value={survey.language} onChange={(event) => set({ language: event.target.value })} /></div></div><div><Label className="field-label">Thank-you message</Label><Textarea rows={3} value={survey.thankYouMessage} onChange={(event) => set({ thankYouMessage: event.target.value })} /></div></CardContent></Card><Card className="h-fit"><CardHeader><CardTitle>Collection policy</CardTitle><CardDescription>Privacy-minded defaults for public feedback.</CardDescription></CardHeader><CardContent className="space-y-4">{[
    ['anonymous', 'Anonymous responses', 'Do not require identifying details.'], ['allowPartial', 'Save partial responses', 'Keep progress for dropout analysis.'], ['showProgress', 'Show progress', 'Tell respondents how far they have left.']
  ].map(([key, title, note]) => <label className="flex items-start gap-3 border-b pb-4 last:border-0 last:pb-0" key={key}><input type="checkbox" className="mt-1 rounded border-input" checked={survey.settings?.[key] !== false} onChange={(event) => set({ settings: { ...survey.settings, [key]: event.target.checked } })} /><span className="text-sm"><span className="font-medium">{title}</span><span className="mt-0.5 block text-xs text-muted-foreground">{note}</span></span></label>)}</CardContent></Card></div>;
}
